# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import runtime_runner_terminal_pb2 as runtime__runner__terminal__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in runtime_runner_terminal_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RuntimeRunnerTerminalStub:
    """Each admitted interactive Terminal owns one independent outbound Runner RPC."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectTerminal = channel.stream_stream(
            "/azents.runtime_control.v1.RuntimeRunnerTerminal/ConnectTerminal",
            request_serializer=runtime__runner__terminal__pb2.RunnerTerminalMessage.SerializeToString,
            response_deserializer=runtime__runner__terminal__pb2.TerminalControlMessage.FromString,
            _registered_method=True,
        )


class RuntimeRunnerTerminalServicer:
    """Each admitted interactive Terminal owns one independent outbound Runner RPC."""

    def ConnectTerminal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RuntimeRunnerTerminalServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ConnectTerminal": grpc.stream_stream_rpc_method_handler(
            servicer.ConnectTerminal,
            request_deserializer=runtime__runner__terminal__pb2.RunnerTerminalMessage.FromString,
            response_serializer=runtime__runner__terminal__pb2.TerminalControlMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "azents.runtime_control.v1.RuntimeRunnerTerminal", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "azents.runtime_control.v1.RuntimeRunnerTerminal", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RuntimeRunnerTerminal:
    """Each admitted interactive Terminal owns one independent outbound Runner RPC."""

    @staticmethod
    def ConnectTerminal(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/azents.runtime_control.v1.RuntimeRunnerTerminal/ConnectTerminal",
            runtime__runner__terminal__pb2.RunnerTerminalMessage.SerializeToString,
            runtime__runner__terminal__pb2.TerminalControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
