# ruff: noqa
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import runtime_stream_session_pb2 as _runtime_stream_session_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(
    _abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta
): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RuntimeStreamGatewaySessionStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RuntimeStreamGatewaySessionAsyncStub: ...
    Connect: _grpc.StreamStreamMultiCallable[
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
    ]

@_typing.type_check_only
class RuntimeStreamGatewaySessionAsyncStub(RuntimeStreamGatewaySessionStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Connect: _aio.StreamStreamMultiCallable[
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
    ]  # type: ignore[assignment]

class RuntimeStreamGatewaySessionServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Connect(
        self,
        request_iterator: _MaybeAsyncIterator[
            _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope
        ],
        context: _ServicerContext,
    ) -> _typing.Union[
        _abc.Iterator[_runtime_stream_session_pb2.RuntimeStreamSessionEnvelope],
        _abc.AsyncIterator[_runtime_stream_session_pb2.RuntimeStreamSessionEnvelope],
    ]: ...

def add_RuntimeStreamGatewaySessionServicer_to_server(
    servicer: RuntimeStreamGatewaySessionServicer,
    server: _typing.Union[_grpc.Server, _aio.Server],
) -> None: ...

class RuntimeStreamControlSessionStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RuntimeStreamControlSessionAsyncStub: ...
    Relay: _grpc.StreamStreamMultiCallable[
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
    ]

@_typing.type_check_only
class RuntimeStreamControlSessionAsyncStub(RuntimeStreamControlSessionStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Relay: _aio.StreamStreamMultiCallable[
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
    ]  # type: ignore[assignment]

class RuntimeStreamControlSessionServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Relay(
        self,
        request_iterator: _MaybeAsyncIterator[
            _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope
        ],
        context: _ServicerContext,
    ) -> _typing.Union[
        _abc.Iterator[_runtime_stream_session_pb2.RuntimeStreamSessionEnvelope],
        _abc.AsyncIterator[_runtime_stream_session_pb2.RuntimeStreamSessionEnvelope],
    ]: ...

def add_RuntimeStreamControlSessionServicer_to_server(
    servicer: RuntimeStreamControlSessionServicer,
    server: _typing.Union[_grpc.Server, _aio.Server],
) -> None: ...

class RuntimeRunnerStreamSessionStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RuntimeRunnerStreamSessionAsyncStub: ...
    Connect: _grpc.StreamStreamMultiCallable[
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
    ]

@_typing.type_check_only
class RuntimeRunnerStreamSessionAsyncStub(RuntimeRunnerStreamSessionStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Connect: _aio.StreamStreamMultiCallable[
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
        _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope,
    ]  # type: ignore[assignment]

class RuntimeRunnerStreamSessionServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Connect(
        self,
        request_iterator: _MaybeAsyncIterator[
            _runtime_stream_session_pb2.RuntimeStreamSessionEnvelope
        ],
        context: _ServicerContext,
    ) -> _typing.Union[
        _abc.Iterator[_runtime_stream_session_pb2.RuntimeStreamSessionEnvelope],
        _abc.AsyncIterator[_runtime_stream_session_pb2.RuntimeStreamSessionEnvelope],
    ]: ...

def add_RuntimeRunnerStreamSessionServicer_to_server(
    servicer: RuntimeRunnerStreamSessionServicer,
    server: _typing.Union[_grpc.Server, _aio.Server],
) -> None: ...
