# ruff: noqa
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime_configuration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "runtime_configuration.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1bruntime_configuration.proto\x12\x19\x61zents.runtime_control.v1"_\n\x1cRuntimeConfigurationEvidence\x12\x13\n\x0brevision_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x1a\n\x12\x64\x65sired_generation\x18\x03 \x01(\x04"\x8e\x01\n\x1cRuntimeConfigurationEnvelope\x12I\n\x08\x65vidence\x18\x01 \x01(\x0b\x32\x37.azents.runtime_control.v1.RuntimeConfigurationEvidence\x12#\n\x1bresolved_configuration_json\x18\x02 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "runtime_configuration_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RUNTIMECONFIGURATIONEVIDENCE"]._serialized_start = 58
    _globals["_RUNTIMECONFIGURATIONEVIDENCE"]._serialized_end = 153
    _globals["_RUNTIMECONFIGURATIONENVELOPE"]._serialized_start = 156
    _globals["_RUNTIMECONFIGURATIONENVELOPE"]._serialized_end = 298
# @@protoc_insertion_point(module_scope)
