# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import runtime_stream_session_pb2 as runtime__stream__session__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in runtime_stream_session_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RuntimeStreamGatewaySessionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
            "/azents.runtime_control.v1.RuntimeStreamGatewaySession/Connect",
            request_serializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
            response_deserializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            _registered_method=True,
        )


class RuntimeStreamGatewaySessionServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RuntimeStreamGatewaySessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Connect": grpc.stream_stream_rpc_method_handler(
            servicer.Connect,
            request_deserializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            response_serializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "azents.runtime_control.v1.RuntimeStreamGatewaySession", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "azents.runtime_control.v1.RuntimeStreamGatewaySession", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RuntimeStreamGatewaySession:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/azents.runtime_control.v1.RuntimeStreamGatewaySession/Connect",
            runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
            runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class RuntimeStreamControlSessionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Relay = channel.stream_stream(
            "/azents.runtime_control.v1.RuntimeStreamControlSession/Relay",
            request_serializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
            response_deserializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            _registered_method=True,
        )


class RuntimeStreamControlSessionServicer:
    """Missing associated documentation comment in .proto file."""

    def Relay(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RuntimeStreamControlSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Relay": grpc.stream_stream_rpc_method_handler(
            servicer.Relay,
            request_deserializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            response_serializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "azents.runtime_control.v1.RuntimeStreamControlSession", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "azents.runtime_control.v1.RuntimeStreamControlSession", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RuntimeStreamControlSession:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Relay(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/azents.runtime_control.v1.RuntimeStreamControlSession/Relay",
            runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
            runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class RuntimeRunnerStreamSessionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
            "/azents.runtime_control.v1.RuntimeRunnerStreamSession/Connect",
            request_serializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
            response_deserializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            _registered_method=True,
        )


class RuntimeRunnerStreamSessionServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RuntimeRunnerStreamSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Connect": grpc.stream_stream_rpc_method_handler(
            servicer.Connect,
            request_deserializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            response_serializer=runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "azents.runtime_control.v1.RuntimeRunnerStreamSession", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "azents.runtime_control.v1.RuntimeRunnerStreamSession", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RuntimeRunnerStreamSession:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/azents.runtime_control.v1.RuntimeRunnerStreamSession/Connect",
            runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.SerializeToString,
            runtime__stream__session__pb2.RuntimeStreamSessionEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
