"""Shared Agent Runtime Control contracts."""

from azents_runtime_control.grpc_provider_client import (
    GrpcProviderControlClient,
    ProviderControlStream,
    RuntimeProviderControlStreamClosed,
    json_value_from_struct,
    provider_report_from_message,
)
from azents_runtime_control.provider import (
    JsonValue,
    ProviderCommandCompletion,
    ProviderCommandEnvelope,
    ProviderConnectionRejected,
    ProviderControlClient,
    ProviderRegistration,
    ProviderRegistrationAccepted,
    ProviderRunLoop,
    RuntimeContainerAuth,
    RuntimeDesiredState,
    RuntimeIdentity,
    RuntimeLifecycleCommand,
    RuntimeLifecycleCommandType,
    RuntimeLifecycleResult,
    RuntimeProviderLifecycle,
    RuntimeProviderObservedState,
    RuntimeProviderReport,
)

__all__ = [
    "GrpcProviderControlClient",
    "JsonValue",
    "ProviderCommandCompletion",
    "ProviderCommandEnvelope",
    "ProviderConnectionRejected",
    "ProviderControlClient",
    "ProviderControlStream",
    "ProviderRegistration",
    "ProviderRegistrationAccepted",
    "ProviderRunLoop",
    "RuntimeContainerAuth",
    "RuntimeDesiredState",
    "RuntimeIdentity",
    "RuntimeLifecycleCommand",
    "RuntimeLifecycleCommandType",
    "RuntimeLifecycleResult",
    "RuntimeProviderLifecycle",
    "RuntimeProviderObservedState",
    "RuntimeProviderReport",
    "RuntimeProviderControlStreamClosed",
    "json_value_from_struct",
    "provider_report_from_message",
]
