# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from azentsadminclient.models.runtime_profile_lifecycle import RuntimeProfileLifecycle
from typing import Optional, Set
from typing_extensions import Self

class RuntimeInfrastructureProfileDeletionReferenceResponse(BaseModel):
    """
    One current Workspace Runtime Profile reference and bounded usage.
    """ # noqa: E501
    workspace_id: StrictStr
    workspace_name: StrictStr
    workspace_handle: StrictStr
    workspace_runtime_profile_id: StrictStr
    workspace_runtime_profile_display_name: StrictStr
    workspace_runtime_profile_lifecycle: RuntimeProfileLifecycle
    workspace_runtime_profile_version: Annotated[int, Field(strict=True, ge=1)]
    selected_agent_count: Annotated[int, Field(strict=True, ge=0)]
    running_runtime_count: Annotated[int, Field(strict=True, ge=0)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["workspace_id", "workspace_name", "workspace_handle", "workspace_runtime_profile_id", "workspace_runtime_profile_display_name", "workspace_runtime_profile_lifecycle", "workspace_runtime_profile_version", "selected_agent_count", "running_runtime_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeInfrastructureProfileDeletionReferenceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeInfrastructureProfileDeletionReferenceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "workspace_name": obj.get("workspace_name"),
            "workspace_handle": obj.get("workspace_handle"),
            "workspace_runtime_profile_id": obj.get("workspace_runtime_profile_id"),
            "workspace_runtime_profile_display_name": obj.get("workspace_runtime_profile_display_name"),
            "workspace_runtime_profile_lifecycle": obj.get("workspace_runtime_profile_lifecycle"),
            "workspace_runtime_profile_version": obj.get("workspace_runtime_profile_version"),
            "selected_agent_count": obj.get("selected_agent_count"),
            "running_runtime_count": obj.get("running_runtime_count")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


