# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RuntimeProviderLifecycleState(str, Enum):
    """
    Permanent administrative lifecycle for a Runtime Provider.
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    DECOMMISSIONING = 'decommissioning'
    DECOMMISSIONED = 'decommissioned'
    FORCE_RETIRED = 'force_retired'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RuntimeProviderLifecycleState from a JSON string"""
        return cls(json.loads(json_str))


