# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from azentsadminclient.models.runtime_execution_audit_event_type import RuntimeExecutionAuditEventType
from azentsadminclient.models.runtime_execution_change_direction import RuntimeExecutionChangeDirection
from azentsadminclient.models.runtime_execution_management_layer import RuntimeExecutionManagementLayer
from typing import Optional, Set
from typing_extensions import Self

class RuntimeExecutionPolicyAuditEventResponse(BaseModel):
    """
    Metadata-only execution-policy audit event.
    """ # noqa: E501
    id: StrictStr
    event_type: RuntimeExecutionAuditEventType
    management_layer: RuntimeExecutionManagementLayer
    target_id: StrictStr
    correlation_id: StrictStr
    classification: RuntimeExecutionChangeDirection
    changed_paths: List[StrictStr]
    impact_counts: Dict[str, StrictInt]
    reason_code: StrictStr
    outcome_code: StrictStr
    workspace_id: Optional[StrictStr]
    agent_id: Optional[StrictStr]
    runtime_id: Optional[StrictStr]
    actor_user_id: Optional[StrictStr]
    actor_workspace_user_id: Optional[StrictStr]
    system_authority: StrictBool
    before_digest: Optional[StrictStr]
    after_digest: Optional[StrictStr]
    created_at: datetime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "event_type", "management_layer", "target_id", "correlation_id", "classification", "changed_paths", "impact_counts", "reason_code", "outcome_code", "workspace_id", "agent_id", "runtime_id", "actor_user_id", "actor_workspace_user_id", "system_authority", "before_digest", "after_digest", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeExecutionPolicyAuditEventResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if workspace_id (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_id is None and "workspace_id" in self.model_fields_set:
            _dict['workspace_id'] = None

        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agent_id'] = None

        # set to None if runtime_id (nullable) is None
        # and model_fields_set contains the field
        if self.runtime_id is None and "runtime_id" in self.model_fields_set:
            _dict['runtime_id'] = None

        # set to None if actor_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.actor_user_id is None and "actor_user_id" in self.model_fields_set:
            _dict['actor_user_id'] = None

        # set to None if actor_workspace_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.actor_workspace_user_id is None and "actor_workspace_user_id" in self.model_fields_set:
            _dict['actor_workspace_user_id'] = None

        # set to None if before_digest (nullable) is None
        # and model_fields_set contains the field
        if self.before_digest is None and "before_digest" in self.model_fields_set:
            _dict['before_digest'] = None

        # set to None if after_digest (nullable) is None
        # and model_fields_set contains the field
        if self.after_digest is None and "after_digest" in self.model_fields_set:
            _dict['after_digest'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeExecutionPolicyAuditEventResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "event_type": obj.get("event_type"),
            "management_layer": obj.get("management_layer"),
            "target_id": obj.get("target_id"),
            "correlation_id": obj.get("correlation_id"),
            "classification": obj.get("classification"),
            "changed_paths": obj.get("changed_paths"),
            "impact_counts": obj.get("impact_counts"),
            "reason_code": obj.get("reason_code"),
            "outcome_code": obj.get("outcome_code"),
            "workspace_id": obj.get("workspace_id"),
            "agent_id": obj.get("agent_id"),
            "runtime_id": obj.get("runtime_id"),
            "actor_user_id": obj.get("actor_user_id"),
            "actor_workspace_user_id": obj.get("actor_workspace_user_id"),
            "system_authority": obj.get("system_authority"),
            "before_digest": obj.get("before_digest"),
            "after_digest": obj.get("after_digest"),
            "created_at": obj.get("created_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


