# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from azentsadminclient.models.runtime_provider_auth_method import RuntimeProviderAuthMethod
from azentsadminclient.models.runtime_provider_binding_owner import RuntimeProviderBindingOwner
from azentsadminclient.models.runtime_provider_binding_state import RuntimeProviderBindingState
from typing import Optional, Set
from typing_extensions import Self

class RuntimeProviderAuthenticationBindingResponse(BaseModel):
    """
    Secret-safe Provider authentication binding.
    """ # noqa: E501
    id: StrictStr
    provider_id: StrictStr
    auth_method: RuntimeProviderAuthMethod
    subject: StrictStr
    state: RuntimeProviderBindingState
    owner: RuntimeProviderBindingOwner
    bootstrap_declaration_id: Optional[StrictStr]
    config: Optional[Dict[str, Any]]
    admin_version: StrictInt
    connected: StrictBool
    last_authenticated_at: Optional[datetime]
    last_connected_at: Optional[datetime]
    revoked_at: Optional[datetime]
    revoked_by_user_id: Optional[StrictStr]
    revocation_reason: Optional[StrictStr]
    created_at: datetime
    updated_at: datetime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "provider_id", "auth_method", "subject", "state", "owner", "bootstrap_declaration_id", "config", "admin_version", "connected", "last_authenticated_at", "last_connected_at", "revoked_at", "revoked_by_user_id", "revocation_reason", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuntimeProviderAuthenticationBindingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if bootstrap_declaration_id (nullable) is None
        # and model_fields_set contains the field
        if self.bootstrap_declaration_id is None and "bootstrap_declaration_id" in self.model_fields_set:
            _dict['bootstrap_declaration_id'] = None

        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if last_authenticated_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_authenticated_at is None and "last_authenticated_at" in self.model_fields_set:
            _dict['last_authenticated_at'] = None

        # set to None if last_connected_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_connected_at is None and "last_connected_at" in self.model_fields_set:
            _dict['last_connected_at'] = None

        # set to None if revoked_at (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_at is None and "revoked_at" in self.model_fields_set:
            _dict['revoked_at'] = None

        # set to None if revoked_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_by_user_id is None and "revoked_by_user_id" in self.model_fields_set:
            _dict['revoked_by_user_id'] = None

        # set to None if revocation_reason (nullable) is None
        # and model_fields_set contains the field
        if self.revocation_reason is None and "revocation_reason" in self.model_fields_set:
            _dict['revocation_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuntimeProviderAuthenticationBindingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "provider_id": obj.get("provider_id"),
            "auth_method": obj.get("auth_method"),
            "subject": obj.get("subject"),
            "state": obj.get("state"),
            "owner": obj.get("owner"),
            "bootstrap_declaration_id": obj.get("bootstrap_declaration_id"),
            "config": obj.get("config"),
            "admin_version": obj.get("admin_version"),
            "connected": obj.get("connected"),
            "last_authenticated_at": obj.get("last_authenticated_at"),
            "last_connected_at": obj.get("last_connected_at"),
            "revoked_at": obj.get("revoked_at"),
            "revoked_by_user_id": obj.get("revoked_by_user_id"),
            "revocation_reason": obj.get("revocation_reason"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


