"""Decode bounded supplementary provider evidence without retaining frames."""

import math
from typing import assert_never

from azents.core.type_guards import is_string_object_dict
from azents.engine.events.pydantic_ai_types import (
    NativeErrorEvidence,
    NativeModelObservation,
    NativeModelProtocol,
    NativeTerminal,
)


def _object(value: object) -> dict[str, object]:
    return value if is_string_object_dict(value) else {}


def _text(value: object) -> str | None:
    return value if isinstance(value, str) else None


def _objects(value: object) -> tuple[dict[str, object], ...]:
    if not isinstance(value, list):
        return ()
    return tuple(item for item in value if is_string_object_dict(item))


def _charge(value: object) -> float | None:
    if isinstance(value, bool) or not isinstance(value, int | float):
        return None
    amount = float(value)
    return amount if math.isfinite(amount) and amount >= 0 else None


def _error(value: object) -> NativeErrorEvidence | None:
    error = _object(value)
    if not error:
        return None
    status = error.get("status_code", error.get("code"))
    return NativeErrorEvidence(
        message=_text(error.get("message")),
        code=_text(error.get("code")) or _text(error.get("status")),
        error_type=_text(error.get("type")),
        parameter=_text(error.get("param")),
        status_code=(
            status
            if isinstance(status, int)
            and not isinstance(status, bool)
            and 100 <= status <= 599
            else None
        ),
    )


def _artifact_item(item: dict[str, object]) -> dict[str, object]:
    """Exclude transient generated bytes from supplementary native artifacts."""
    if item.get("type") == "image_generation_call":
        return {key: value for key, value in item.items() if key != "result"}
    return item


def _output_limit(protocol: NativeModelProtocol) -> NativeErrorEvidence:
    return NativeErrorEvidence(
        message="The model response reached its output token limit.",
        code="max_output_tokens",
        error_type=f"{protocol}.response_incomplete",
        parameter=None,
        status_code=None,
    )


def _policy_refusal(protocol: NativeModelProtocol, code: str) -> NativeErrorEvidence:
    return NativeErrorEvidence(
        message="The model provider refused the response under its content policy.",
        code=code,
        error_type=f"{protocol}.content_policy",
        parameter=None,
        status_code=None,
    )


def observe_native_payload(
    protocol: NativeModelProtocol,
    payload: dict[str, object],
) -> NativeModelObservation:
    """Extract one parsed provider event from an unchanged SDK input stream."""
    event_type = _text(payload.get("type")) or protocol
    terminal: NativeTerminal | None = None
    end_turn = payload.get("end_turn")
    usage: dict[str, object] | None = None
    items: tuple[dict[str, object], ...] = ()
    annotations: tuple[dict[str, object], ...] = ()
    error = _error(payload.get("error"))
    service_tier = _text(payload.get("service_tier"))
    reported_cost = None
    match protocol:
        case "responses":
            response = _object(payload.get("response"))
            if event_type == "response.completed":
                terminal = (
                    "success"
                    if response.get("status", "completed") == "completed"
                    else "incomplete"
                )
                items = tuple(
                    _artifact_item(item) for item in _objects(response.get("output"))
                )
            elif event_type in {"response.failed", "error"}:
                terminal = "failed"
            elif event_type == "response.incomplete":
                terminal = "incomplete"
            if event_type == "response.output_item.done":
                item = _object(payload.get("item"))
                items = (_artifact_item(item),) if item else ()
            if event_type == "response.output_text.annotation.added":
                annotation = _object(payload.get("annotation"))
                annotations = (annotation,) if annotation else ()
            usage = _object(response.get("usage")) or None
            error = error or _error(response.get("error"))
            reason = _text(_object(response.get("incomplete_details")).get("reason"))
            if terminal == "incomplete" and reason == "max_output_tokens":
                error = _output_limit(protocol)
            elif terminal == "incomplete" and reason == "content_filter":
                error = _policy_refusal(protocol, reason)
            nested_end_turn = response.get("end_turn")
            if type(nested_end_turn) is bool:
                end_turn = nested_end_turn
            service_tier = service_tier or _text(response.get("service_tier"))
            reported_cost = _charge(response.get("cost"))
        case "anthropic":
            message = _object(payload.get("message"))
            usage = (
                _object(payload.get("usage")) or _object(message.get("usage")) or None
            )
            if event_type == "message_stop":
                terminal = "success"
            elif event_type == "error":
                terminal = "failed"
            block = _object(payload.get("content_block"))
            if block:
                items = (block,)
            delta = _object(payload.get("delta"))
            reason = _text(delta.get("stop_reason")) or _text(
                message.get("stop_reason")
            )
            if reason == "max_tokens":
                terminal = "incomplete"
                error = _output_limit(protocol)
            elif reason == "refusal":
                terminal = "failed"
                error = _policy_refusal(protocol, reason)
            if delta.get("type") == "citations_delta":
                citation = _object(delta.get("citation"))
                annotations = (citation,) if citation else ()
            service_tier = service_tier or _text(
                _object(message.get("usage")).get("service_tier")
            )
        case "google":
            usage = _object(payload.get("usageMetadata")) or None
            candidates = _objects(payload.get("candidates"))
            for candidate in candidates:
                finish = _text(candidate.get("finishReason"))
                if finish == "STOP" and terminal not in {"failed", "incomplete"}:
                    terminal = "success"
                elif finish == "MAX_TOKENS":
                    terminal = "incomplete"
                    error = _output_limit(protocol)
                elif finish in {
                    "SAFETY",
                    "BLOCKLIST",
                    "PROHIBITED_CONTENT",
                    "SPII",
                    "IMAGE_SAFETY",
                    "IMAGE_PROHIBITED_CONTENT",
                }:
                    terminal = "failed"
                    error = _policy_refusal(protocol, finish)
                elif finish and finish not in {"STOP", "FINISH_REASON_UNSPECIFIED"}:
                    terminal = "failed"
                    error = NativeErrorEvidence(
                        message=None,
                        code=finish,
                        error_type="google.finish_reason",
                        parameter=None,
                        status_code=None,
                    )
                grounding = _object(candidate.get("groundingMetadata"))
                if grounding:
                    items += ({"type": "google_grounding", **grounding},)
            block = _text(_object(payload.get("promptFeedback")).get("blockReason"))
            if block and block != "BLOCK_REASON_UNSPECIFIED":
                terminal = "failed"
                error = _policy_refusal(protocol, block)
            if error is not None and terminal != "incomplete":
                terminal = "failed"
        case "bedrock":
            event_type = next(iter(payload), "bedrock")
            stop = _object(payload.get("messageStop"))
            if stop:
                reason = _text(stop.get("stopReason"))
                terminal = (
                    "success"
                    if reason in {"end_turn", "tool_use", "stop_sequence"}
                    else "failed"
                )
                if reason == "max_tokens":
                    terminal = "incomplete"
                    error = _output_limit(protocol)
                elif reason in {"guardrail_intervened", "content_filtered"}:
                    error = _policy_refusal(protocol, reason)
            metadata = _object(payload.get("metadata"))
            usage = _object(metadata.get("usage")) or None
            if event_type.endswith("Exception"):
                terminal = "failed"
                value = _object(payload.get(event_type))
                error = NativeErrorEvidence(
                    message=_text(value.get("message")),
                    code=event_type,
                    error_type=event_type,
                    parameter=None,
                    status_code=None,
                )
        case "chat_completions":
            usage = _object(payload.get("usage")) or None
            for choice in _objects(payload.get("choices")):
                finish = _text(choice.get("finish_reason"))
                if finish in {
                    "stop",
                    "tool_calls",
                    "function_call",
                } and terminal not in {"failed", "incomplete"}:
                    terminal = "success"
                elif finish == "length":
                    terminal = "incomplete"
                    error = _output_limit(protocol)
                elif finish == "content_filter":
                    terminal = "failed"
                    error = _policy_refusal(protocol, finish)
                elif finish and finish not in {"stop", "tool_calls", "function_call"}:
                    terminal = "failed"
                delta = _object(choice.get("delta"))
                annotations += _objects(delta.get("annotations"))
            if error is not None and terminal != "incomplete":
                terminal = "failed"
        case _:
            assert_never(protocol)
    if usage is not None and reported_cost is None:
        reported_cost = _charge(usage.get("cost"))
    return NativeModelObservation(
        protocol=protocol,
        event_type=event_type,
        parsed_activity=True,
        terminal=terminal,
        end_turn=end_turn if type(end_turn) is bool else None,
        native_usage=usage,
        reported_cost_usd=reported_cost,
        service_tier=service_tier,
        native_items=items,
        annotations=annotations,
        error=error,
    )
