# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.agent_model_selection_input import AgentModelSelectionInput
from azentspublicclient.models.agent_type import AgentType
from azentspublicclient.models.model_parameters import ModelParameters
from azentspublicclient.models.selectable_model_option_input import SelectableModelOptionInput
from azentspublicclient.models.subagent_settings import SubagentSettings
from typing import Optional, Set
from typing_extensions import Self

class AgentCreateRequest(BaseModel):
    """
    Agent creation request.
    """ # noqa: E501
    name: StrictStr = Field(description="Agent name")
    model_selection: Optional[AgentModelSelectionInput] = None
    lightweight_model_selection: Optional[AgentModelSelectionInput] = None
    selectable_model_options: Optional[List[SelectableModelOptionInput]] = None
    main_model_label: Optional[StrictStr] = None
    lightweight_model_label: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    model_parameters: Optional[ModelParameters] = None
    system_prompt: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = Field(default=True, description="Enabled state")
    type: Optional[AgentType] = Field(default=None, description="Visibility scope")
    runtime_provider_id: Optional[StrictStr] = None
    shell_enabled: Optional[StrictBool] = Field(default=True, description="Shell enabled state")
    memory_enabled: Optional[StrictBool] = Field(default=True, description="Memory enabled state")
    tool_search_enabled: Optional[StrictBool] = Field(default=False, description="Tool Search enabled state")
    max_turns: Optional[StrictInt] = None
    subagent_settings: Optional[SubagentSettings] = Field(default=None, description="Subagent execution settings")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "model_selection", "lightweight_model_selection", "selectable_model_options", "main_model_label", "lightweight_model_label", "description", "model_parameters", "system_prompt", "enabled", "type", "runtime_provider_id", "shell_enabled", "memory_enabled", "tool_search_enabled", "max_turns", "subagent_settings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model_selection
        if self.model_selection:
            _dict['model_selection'] = self.model_selection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lightweight_model_selection
        if self.lightweight_model_selection:
            _dict['lightweight_model_selection'] = self.lightweight_model_selection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in selectable_model_options (list)
        _items = []
        if self.selectable_model_options:
            for _item_selectable_model_options in self.selectable_model_options:
                if _item_selectable_model_options:
                    _items.append(_item_selectable_model_options.to_dict())
            _dict['selectable_model_options'] = _items
        # override the default output from pydantic by calling `to_dict()` of model_parameters
        if self.model_parameters:
            _dict['model_parameters'] = self.model_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subagent_settings
        if self.subagent_settings:
            _dict['subagent_settings'] = self.subagent_settings.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if model_selection (nullable) is None
        # and model_fields_set contains the field
        if self.model_selection is None and "model_selection" in self.model_fields_set:
            _dict['model_selection'] = None

        # set to None if lightweight_model_selection (nullable) is None
        # and model_fields_set contains the field
        if self.lightweight_model_selection is None and "lightweight_model_selection" in self.model_fields_set:
            _dict['lightweight_model_selection'] = None

        # set to None if selectable_model_options (nullable) is None
        # and model_fields_set contains the field
        if self.selectable_model_options is None and "selectable_model_options" in self.model_fields_set:
            _dict['selectable_model_options'] = None

        # set to None if main_model_label (nullable) is None
        # and model_fields_set contains the field
        if self.main_model_label is None and "main_model_label" in self.model_fields_set:
            _dict['main_model_label'] = None

        # set to None if lightweight_model_label (nullable) is None
        # and model_fields_set contains the field
        if self.lightweight_model_label is None and "lightweight_model_label" in self.model_fields_set:
            _dict['lightweight_model_label'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if model_parameters (nullable) is None
        # and model_fields_set contains the field
        if self.model_parameters is None and "model_parameters" in self.model_fields_set:
            _dict['model_parameters'] = None

        # set to None if system_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.system_prompt is None and "system_prompt" in self.model_fields_set:
            _dict['system_prompt'] = None

        # set to None if runtime_provider_id (nullable) is None
        # and model_fields_set contains the field
        if self.runtime_provider_id is None and "runtime_provider_id" in self.model_fields_set:
            _dict['runtime_provider_id'] = None

        # set to None if max_turns (nullable) is None
        # and model_fields_set contains the field
        if self.max_turns is None and "max_turns" in self.model_fields_set:
            _dict['max_turns'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "model_selection": AgentModelSelectionInput.from_dict(obj["model_selection"]) if obj.get("model_selection") is not None else None,
            "lightweight_model_selection": AgentModelSelectionInput.from_dict(obj["lightweight_model_selection"]) if obj.get("lightweight_model_selection") is not None else None,
            "selectable_model_options": [SelectableModelOptionInput.from_dict(_item) for _item in obj["selectable_model_options"]] if obj.get("selectable_model_options") is not None else None,
            "main_model_label": obj.get("main_model_label"),
            "lightweight_model_label": obj.get("lightweight_model_label"),
            "description": obj.get("description"),
            "model_parameters": ModelParameters.from_dict(obj["model_parameters"]) if obj.get("model_parameters") is not None else None,
            "system_prompt": obj.get("system_prompt"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "type": obj.get("type"),
            "runtime_provider_id": obj.get("runtime_provider_id"),
            "shell_enabled": obj.get("shell_enabled") if obj.get("shell_enabled") is not None else True,
            "memory_enabled": obj.get("memory_enabled") if obj.get("memory_enabled") is not None else True,
            "tool_search_enabled": obj.get("tool_search_enabled") if obj.get("tool_search_enabled") is not None else False,
            "max_turns": obj.get("max_turns"),
            "subagent_settings": SubagentSettings.from_dict(obj["subagent_settings"]) if obj.get("subagent_settings") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


