# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.toolkit_config_response import ToolkitConfigResponse
from typing import Optional, Set
from typing_extensions import Self

class AgentToolkitManagementItemResponse(BaseModel):
    """
    One Toolkit in the authorized Agent management projection.
    """ # noqa: E501
    ownership_scope: StrictStr
    toolkit: ToolkitConfigResponse
    agent_toolkit_id: Optional[StrictStr]
    readiness: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["ownership_scope", "toolkit", "agent_toolkit_id", "readiness"]

    @field_validator('ownership_scope')
    def ownership_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['workspace_shared', 'agent_only']):
            raise ValueError("must be one of enum values ('workspace_shared', 'agent_only')")
        return value

    @field_validator('readiness')
    def readiness_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ready', 'authorization_required', 'disabled']):
            raise ValueError("must be one of enum values ('ready', 'authorization_required', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentToolkitManagementItemResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of toolkit
        if self.toolkit:
            _dict['toolkit'] = self.toolkit.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if agent_toolkit_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_toolkit_id is None and "agent_toolkit_id" in self.model_fields_set:
            _dict['agent_toolkit_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentToolkitManagementItemResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ownership_scope": obj.get("ownership_scope"),
            "toolkit": ToolkitConfigResponse.from_dict(obj["toolkit"]) if obj.get("toolkit") is not None else None,
            "agent_toolkit_id": obj.get("agent_toolkit_id"),
            "readiness": obj.get("readiness")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


