# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AgentWorkspaceStatResponse(BaseModel):
    """
    Agent Workspace path metadata response.
    """ # noqa: E501
    path: StrictStr = Field(description="Agent Workspace path")
    name: StrictStr = Field(description="Path basename")
    kind: StrictStr = Field(description="Path kind")
    size: Optional[StrictInt] = None
    media_type: Optional[StrictStr] = None
    modified_at: Optional[datetime] = None
    symlink: StrictBool = Field(description="Whether the path itself is a symlink")
    real_path: Optional[StrictStr] = None
    resolved_kind: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["path", "name", "kind", "size", "media_type", "modified_at", "symlink", "real_path", "resolved_kind"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['file', 'directory', 'symlink', 'other', 'missing']):
            raise ValueError("must be one of enum values ('file', 'directory', 'symlink', 'other', 'missing')")
        return value

    @field_validator('resolved_kind')
    def resolved_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['file', 'directory', 'symlink', 'other', 'missing']):
            raise ValueError("must be one of enum values ('file', 'directory', 'symlink', 'other', 'missing')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentWorkspaceStatResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict['size'] = None

        # set to None if media_type (nullable) is None
        # and model_fields_set contains the field
        if self.media_type is None and "media_type" in self.model_fields_set:
            _dict['media_type'] = None

        # set to None if modified_at (nullable) is None
        # and model_fields_set contains the field
        if self.modified_at is None and "modified_at" in self.model_fields_set:
            _dict['modified_at'] = None

        # set to None if real_path (nullable) is None
        # and model_fields_set contains the field
        if self.real_path is None and "real_path" in self.model_fields_set:
            _dict['real_path'] = None

        # set to None if resolved_kind (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_kind is None and "resolved_kind" in self.model_fields_set:
            _dict['resolved_kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentWorkspaceStatResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "name": obj.get("name"),
            "kind": obj.get("kind"),
            "size": obj.get("size"),
            "media_type": obj.get("media_type"),
            "modified_at": obj.get("modified_at"),
            "symlink": obj.get("symlink"),
            "real_path": obj.get("real_path"),
            "resolved_kind": obj.get("resolved_kind")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


