# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from azentspublicclient.models.agent_session_response import AgentSessionResponse
from typing import Optional, Set
from typing_extensions import Self

class AgentSessionSidebarResponse(BaseModel):
    """
    Bounded Agent sidebar session response.
    """ # noqa: E501
    pinned: List[AgentSessionResponse] = Field(description="All pinned active root sessions")
    recent: List[AgentSessionResponse] = Field(description="Distinct recent non-pinned active root sessions")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["pinned", "recent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentSessionSidebarResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pinned (list)
        _items = []
        if self.pinned:
            for _item_pinned in self.pinned:
                if _item_pinned:
                    _items.append(_item_pinned.to_dict())
            _dict['pinned'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recent (list)
        _items = []
        if self.recent:
            for _item_recent in self.recent:
                if _item_recent:
                    _items.append(_item_recent.to_dict())
            _dict['recent'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentSessionSidebarResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pinned": [AgentSessionResponse.from_dict(_item) for _item in obj["pinned"]] if obj.get("pinned") is not None else None,
            "recent": [AgentSessionResponse.from_dict(_item) for _item in obj["recent"]] if obj.get("recent") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


