# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.agent_runtime_lifecycle_provider_response import AgentRuntimeLifecycleProviderResponse
from azentspublicclient.models.agent_runtime_lifecycle_runner_response import AgentRuntimeLifecycleRunnerResponse
from azentspublicclient.models.runtime_desired_state import RuntimeDesiredState
from typing import Optional, Set
from typing_extensions import Self

class AgentRuntimeLifecyclePresentationResponse(BaseModel):
    """
    Server-authoritative Runtime lifecycle presentation.
    """ # noqa: E501
    target: RuntimeDesiredState
    convergence: StrictStr
    provider: AgentRuntimeLifecycleProviderResponse
    runner: AgentRuntimeLifecycleRunnerResponse
    availability: StrictStr
    reason_code: Optional[StrictStr]
    desired_generation: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["target", "convergence", "provider", "runner", "availability", "reason_code", "desired_generation"]

    @field_validator('convergence')
    def convergence_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['stable', 'starting', 'stopping', 'resetting', 'recovering', 'blocked', 'failed']):
            raise ValueError("must be one of enum values ('stable', 'starting', 'stopping', 'resetting', 'recovering', 'blocked', 'failed')")
        return value

    @field_validator('availability')
    def availability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ready', 'stopped', 'transitioning', 'provider_disconnected', 'runner_unavailable', 'configuration_blocked', 'failed', 'removing']):
            raise ValueError("must be one of enum values ('ready', 'stopped', 'transitioning', 'provider_disconnected', 'runner_unavailable', 'configuration_blocked', 'failed', 'removing')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentRuntimeLifecyclePresentationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of provider
        if self.provider:
            _dict['provider'] = self.provider.to_dict()
        # override the default output from pydantic by calling `to_dict()` of runner
        if self.runner:
            _dict['runner'] = self.runner.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if reason_code (nullable) is None
        # and model_fields_set contains the field
        if self.reason_code is None and "reason_code" in self.model_fields_set:
            _dict['reason_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentRuntimeLifecyclePresentationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "target": obj.get("target"),
            "convergence": obj.get("convergence"),
            "provider": AgentRuntimeLifecycleProviderResponse.from_dict(obj["provider"]) if obj.get("provider") is not None else None,
            "runner": AgentRuntimeLifecycleRunnerResponse.from_dict(obj["runner"]) if obj.get("runner") is not None else None,
            "availability": obj.get("availability"),
            "reason_code": obj.get("reason_code"),
            "desired_generation": obj.get("desired_generation")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


