# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.event_kind import EventKind
from azentspublicclient.models.inference_run_summary import InferenceRunSummary
from typing import Optional, Set
from typing_extensions import Self

class ChatEventResponse(BaseModel):
    """
    Event chat event response.
    """ # noqa: E501
    id: StrictStr = Field(description="Event ID")
    session_id: StrictStr = Field(description="AgentSession ID")
    kind: EventKind = Field(description="Event kind")
    payload: Dict[str, Any] = Field(description="Event payload")
    model_order: StrictInt = Field(description="Model input logical order")
    external_id: Optional[StrictStr] = None
    adapter: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    model: Optional[StrictStr] = None
    native_format: Optional[StrictStr] = None
    schema_version: StrictStr = Field(description="Event schema version")
    created_at: datetime = Field(description="Created at")
    inference_run_summary: Optional[InferenceRunSummary] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "session_id", "kind", "payload", "model_order", "external_id", "adapter", "provider", "model", "native_format", "schema_version", "created_at", "inference_run_summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChatEventResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of inference_run_summary
        if self.inference_run_summary:
            _dict['inference_run_summary'] = self.inference_run_summary.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if adapter (nullable) is None
        # and model_fields_set contains the field
        if self.adapter is None and "adapter" in self.model_fields_set:
            _dict['adapter'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if native_format (nullable) is None
        # and model_fields_set contains the field
        if self.native_format is None and "native_format" in self.model_fields_set:
            _dict['native_format'] = None

        # set to None if inference_run_summary (nullable) is None
        # and model_fields_set contains the field
        if self.inference_run_summary is None and "inference_run_summary" in self.model_fields_set:
            _dict['inference_run_summary'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChatEventResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "session_id": obj.get("session_id"),
            "kind": obj.get("kind"),
            "payload": obj.get("payload"),
            "model_order": obj.get("model_order"),
            "external_id": obj.get("external_id"),
            "adapter": obj.get("adapter"),
            "provider": obj.get("provider"),
            "model": obj.get("model"),
            "native_format": obj.get("native_format"),
            "schema_version": obj.get("schema_version"),
            "created_at": obj.get("created_at"),
            "inference_run_summary": InferenceRunSummary.from_dict(obj["inference_run_summary"]) if obj.get("inference_run_summary") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


