# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExternalChannelBindingActivationStatus(str, Enum):
    """
    Initial invocation activation state for one active binding.
    """

    """
    allowed enum values
    """
    WAITING_HYDRATION = 'waiting_hydration'
    ACTIVE = 'active'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExternalChannelBindingActivationStatus from a JSON string"""
        return cls(json.loads(json_str))


