# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from azentspublicclient.models.kubernetes_container_resources import KubernetesContainerResources
from azentspublicclient.models.kubernetes_din_d_module import KubernetesDinDModule
from azentspublicclient.models.kubernetes_scheduling_module import KubernetesSchedulingModule
from azentspublicclient.models.kubernetes_workspace_volume import KubernetesWorkspaceVolume
from azentspublicclient.models.runtime_network_policy_module import RuntimeNetworkPolicyModule
from typing import Optional, Set
from typing_extensions import Self

class KubernetesPodProfileSpecV1(BaseModel):
    """
    Kubernetes Pod Profile contract version 1.
    """ # noqa: E501
    profile_kind: StrictStr
    contract_family: StrictStr
    schema_version: StrictInt
    runner_resources: KubernetesContainerResources
    workspace_volume: KubernetesWorkspaceVolume
    network_policy: RuntimeNetworkPolicyModule
    service_account_name: Optional[Annotated[str, Field(strict=True, max_length=253)]]
    scheduling: KubernetesSchedulingModule
    dind: Optional[KubernetesDinDModule]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["profile_kind", "contract_family", "schema_version", "runner_resources", "workspace_volume", "network_policy", "service_account_name", "scheduling", "dind"]

    @field_validator('profile_kind')
    def profile_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['kubernetes_pod']):
            raise ValueError("must be one of enum values ('kubernetes_pod')")
        return value

    @field_validator('contract_family')
    def contract_family_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['kubernetes.pod-profile']):
            raise ValueError("must be one of enum values ('kubernetes.pod-profile')")
        return value

    @field_validator('schema_version')
    def schema_version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([1]):
            raise ValueError("must be one of enum values (1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KubernetesPodProfileSpecV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of runner_resources
        if self.runner_resources:
            _dict['runner_resources'] = self.runner_resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workspace_volume
        if self.workspace_volume:
            _dict['workspace_volume'] = self.workspace_volume.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network_policy
        if self.network_policy:
            _dict['network_policy'] = self.network_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scheduling
        if self.scheduling:
            _dict['scheduling'] = self.scheduling.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dind
        if self.dind:
            _dict['dind'] = self.dind.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if service_account_name (nullable) is None
        # and model_fields_set contains the field
        if self.service_account_name is None and "service_account_name" in self.model_fields_set:
            _dict['service_account_name'] = None

        # set to None if dind (nullable) is None
        # and model_fields_set contains the field
        if self.dind is None and "dind" in self.model_fields_set:
            _dict['dind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KubernetesPodProfileSpecV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "profile_kind": obj.get("profile_kind"),
            "contract_family": obj.get("contract_family"),
            "schema_version": obj.get("schema_version"),
            "runner_resources": KubernetesContainerResources.from_dict(obj["runner_resources"]) if obj.get("runner_resources") is not None else None,
            "workspace_volume": KubernetesWorkspaceVolume.from_dict(obj["workspace_volume"]) if obj.get("workspace_volume") is not None else None,
            "network_policy": RuntimeNetworkPolicyModule.from_dict(obj["network_policy"]) if obj.get("network_policy") is not None else None,
            "service_account_name": obj.get("service_account_name"),
            "scheduling": KubernetesSchedulingModule.from_dict(obj["scheduling"]) if obj.get("scheduling") is not None else None,
            "dind": KubernetesDinDModule.from_dict(obj["dind"]) if obj.get("dind") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


