# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.agent_session_run_state import AgentSessionRunState
from azentspublicclient.models.chat_event_response import ChatEventResponse
from azentspublicclient.models.chat_live_run_state_response import ChatLiveRunStateResponse
from azentspublicclient.models.goal_state_response import GoalStateResponse
from azentspublicclient.models.partial_history_response import PartialHistoryResponse
from azentspublicclient.models.todo_state_response import TodoStateResponse
from typing import Optional, Set
from typing_extensions import Self

class LiveEventListResponse(BaseModel):
    """
    Current live state taxonomy snapshot response.
    """ # noqa: E501
    partial_history: PartialHistoryResponse = Field(description="Partial history projection list to compose into Chat timeline")
    input_buffers: List[ChatEventResponse] = Field(description="Pending input buffer projection list")
    run: Optional[ChatLiveRunStateResponse] = None
    session_run_state: AgentSessionRunState = Field(description="Authoritative run_state for the current session")
    todo: Optional[TodoStateResponse] = None
    goal: Optional[GoalStateResponse] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["partial_history", "input_buffers", "run", "session_run_state", "todo", "goal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LiveEventListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of partial_history
        if self.partial_history:
            _dict['partial_history'] = self.partial_history.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in input_buffers (list)
        _items = []
        if self.input_buffers:
            for _item_input_buffers in self.input_buffers:
                if _item_input_buffers:
                    _items.append(_item_input_buffers.to_dict())
            _dict['input_buffers'] = _items
        # override the default output from pydantic by calling `to_dict()` of run
        if self.run:
            _dict['run'] = self.run.to_dict()
        # override the default output from pydantic by calling `to_dict()` of todo
        if self.todo:
            _dict['todo'] = self.todo.to_dict()
        # override the default output from pydantic by calling `to_dict()` of goal
        if self.goal:
            _dict['goal'] = self.goal.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if run (nullable) is None
        # and model_fields_set contains the field
        if self.run is None and "run" in self.model_fields_set:
            _dict['run'] = None

        # set to None if todo (nullable) is None
        # and model_fields_set contains the field
        if self.todo is None and "todo" in self.model_fields_set:
            _dict['todo'] = None

        # set to None if goal (nullable) is None
        # and model_fields_set contains the field
        if self.goal is None and "goal" in self.model_fields_set:
            _dict['goal'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LiveEventListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "partial_history": PartialHistoryResponse.from_dict(obj["partial_history"]) if obj.get("partial_history") is not None else None,
            "input_buffers": [ChatEventResponse.from_dict(_item) for _item in obj["input_buffers"]] if obj.get("input_buffers") is not None else None,
            "run": ChatLiveRunStateResponse.from_dict(obj["run"]) if obj.get("run") is not None else None,
            "session_run_state": obj.get("session_run_state"),
            "todo": TodoStateResponse.from_dict(obj["todo"]) if obj.get("todo") is not None else None,
            "goal": GoalStateResponse.from_dict(obj["goal"]) if obj.get("goal") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
