# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.model_feature_condition import ModelFeatureCondition
from azentspublicclient.models.reasoning_effort_value import ReasoningEffortValue
from typing import Optional, Set
from typing_extensions import Self

class ModelRequestConstraints(BaseModel):
    """
    Known request metadata, independent of final feature membership.  A missing default is omitted knowledge, not another feature support state. The final capability fields alone determine whether a feature is present.
    """ # noqa: E501
    known_default: Optional[ReasoningEffortValue] = None
    feature_conditions: Optional[List[ModelFeatureCondition]] = None
    __properties: ClassVar[List[str]] = ["known_default", "feature_conditions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelRequestConstraints from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in feature_conditions (list)
        _items = []
        if self.feature_conditions:
            for _item_feature_conditions in self.feature_conditions:
                if _item_feature_conditions:
                    _items.append(_item_feature_conditions.to_dict())
            _dict['feature_conditions'] = _items
        # set to None if known_default (nullable) is None
        # and model_fields_set contains the field
        if self.known_default is None and "known_default" in self.model_fields_set:
            _dict['known_default'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelRequestConstraints from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # Preserve omission while retaining generated nested-field conversion.
        _obj = cls.model_validate({
            _key: _value for _key, _value in {
            "known_default": obj.get("known_default"),
            "feature_conditions": [ModelFeatureCondition.from_dict(_item) for _item in obj["feature_conditions"]] if obj.get("feature_conditions") is not None else None
            }.items() if _key in obj
        })
        return _obj


