# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RuntimeTerminalDeleteAcknowledgementKind(str, Enum):
    """
    Authority that proved one terminal Runtime deletion.
    """

    """
    allowed enum values
    """
    PROVIDER_REPORT = 'provider_report'
    NO_PHYSICAL_BINDING = 'no_physical_binding'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RuntimeTerminalDeleteAcknowledgementKind from a JSON string"""
        return cls(json.loads(json_str))


