# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RuntimeTerminalTicketStatus(str, Enum):
    """
    Ticket issuance result without Runtime side effects.
    """

    """
    allowed enum values
    """
    ISSUED = 'issued'
    RUNTIME_STOPPED = 'runtime_stopped'
    UNAVAILABLE = 'unavailable'
    DENIED = 'denied'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RuntimeTerminalTicketStatus from a JSON string"""
        return cls(json.loads(json_str))


