# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from azentspublicclient.models.external_channel_transport import ExternalChannelTransport
from typing import Optional, Set
from typing_extensions import Self

class SlackManifestGuidance(BaseModel):
    """
    SlackManifestGuidance
    """ # noqa: E501
    provider: Optional[StrictStr] = 'slack'
    transport: ExternalChannelTransport
    bot_scopes: List[StrictStr]
    event_subscriptions: List[StrictStr]
    socket_mode_enabled: StrictBool
    app_token_scope: Optional[StrictStr]
    callback_url: Optional[StrictStr]
    manifest: Dict[str, Any]
    manifest_json: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["provider", "transport", "bot_scopes", "event_subscriptions", "socket_mode_enabled", "app_token_scope", "callback_url", "manifest", "manifest_json"]

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['slack']):
            raise ValueError("must be one of enum values ('slack')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SlackManifestGuidance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if app_token_scope (nullable) is None
        # and model_fields_set contains the field
        if self.app_token_scope is None and "app_token_scope" in self.model_fields_set:
            _dict['app_token_scope'] = None

        # set to None if callback_url (nullable) is None
        # and model_fields_set contains the field
        if self.callback_url is None and "callback_url" in self.model_fields_set:
            _dict['callback_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SlackManifestGuidance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider": obj.get("provider") if obj.get("provider") is not None else 'slack',
            "transport": obj.get("transport"),
            "bot_scopes": obj.get("bot_scopes"),
            "event_subscriptions": obj.get("event_subscriptions"),
            "socket_mode_enabled": obj.get("socket_mode_enabled"),
            "app_token_scope": obj.get("app_token_scope"),
            "callback_url": obj.get("callback_url"),
            "manifest": obj.get("manifest"),
            "manifest_json": obj.get("manifest_json")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


