# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from azentspublicclient.models.subscription_usage_available_response_financial_details import SubscriptionUsageAvailableResponseFinancialDetails
from azentspublicclient.models.subscription_usage_limit_response import SubscriptionUsageLimitResponse
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionUsageAvailableResponse(BaseModel):
    """
    Public available subscription usage response.
    """ # noqa: E501
    type: StrictStr
    integration_id: StrictStr
    provider: StrictStr
    fetched_at: datetime
    plan_label: Optional[StrictStr]
    limits: Annotated[List[SubscriptionUsageLimitResponse], Field(min_length=1)]
    financial_details: Optional[SubscriptionUsageAvailableResponseFinancialDetails]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "integration_id", "provider", "fetched_at", "plan_label", "limits", "financial_details"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['available']):
            raise ValueError("must be one of enum values ('available')")
        return value

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['chatgpt_oauth', 'xai_oauth', 'openrouter', 'kimi_oauth']):
            raise ValueError("must be one of enum values ('chatgpt_oauth', 'xai_oauth', 'openrouter', 'kimi_oauth')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionUsageAvailableResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in limits (list)
        _items = []
        if self.limits:
            for _item_limits in self.limits:
                if _item_limits:
                    _items.append(_item_limits.to_dict())
            _dict['limits'] = _items
        # override the default output from pydantic by calling `to_dict()` of financial_details
        if self.financial_details:
            _dict['financial_details'] = self.financial_details.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if plan_label (nullable) is None
        # and model_fields_set contains the field
        if self.plan_label is None and "plan_label" in self.model_fields_set:
            _dict['plan_label'] = None

        # set to None if financial_details (nullable) is None
        # and model_fields_set contains the field
        if self.financial_details is None and "financial_details" in self.model_fields_set:
            _dict['financial_details'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionUsageAvailableResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "integration_id": obj.get("integration_id"),
            "provider": obj.get("provider"),
            "fetched_at": obj.get("fetched_at"),
            "plan_label": obj.get("plan_label"),
            "limits": [SubscriptionUsageLimitResponse.from_dict(_item) for _item in obj["limits"]] if obj.get("limits") is not None else None,
            "financial_details": SubscriptionUsageAvailableResponseFinancialDetails.from_dict(obj["financial_details"]) if obj.get("financial_details") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


