# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from azentspublicclient.models.runtime_profile_lifecycle import RuntimeProfileLifecycle
from azentspublicclient.models.workspace_runtime_profile_policy import WorkspaceRuntimeProfilePolicy
from typing import Optional, Set
from typing_extensions import Self

class WorkspaceRuntimeProfileReplaceRequest(BaseModel):
    """
    Complete optimistic replacement of one Workspace Runtime Profile.
    """ # noqa: E501
    expected_version: Annotated[int, Field(strict=True, ge=1)]
    infrastructure_profile_id: StrictStr
    display_name: Annotated[str, Field(min_length=1, strict=True, max_length=120)]
    description: Annotated[str, Field(strict=True, max_length=4000)]
    lifecycle: RuntimeProfileLifecycle
    policy: WorkspaceRuntimeProfilePolicy
    terminal_enabled: StrictBool
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["expected_version", "infrastructure_profile_id", "display_name", "description", "lifecycle", "policy", "terminal_enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceRuntimeProfileReplaceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceRuntimeProfileReplaceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "expected_version": obj.get("expected_version"),
            "infrastructure_profile_id": obj.get("infrastructure_profile_id"),
            "display_name": obj.get("display_name"),
            "description": obj.get("description"),
            "lifecycle": obj.get("lifecycle"),
            "policy": WorkspaceRuntimeProfilePolicy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "terminal_enabled": obj.get("terminal_enabled")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


