# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from azentspublicclient.models.workspace_runtime_network_restriction_direct import WorkspaceRuntimeNetworkRestrictionDirect
from azentspublicclient.models.workspace_runtime_network_restriction_inherit import WorkspaceRuntimeNetworkRestrictionInherit
from azentspublicclient.models.workspace_runtime_network_restriction_no_network import WorkspaceRuntimeNetworkRestrictionNoNetwork
from azentspublicclient.models.workspace_runtime_network_restriction_proxy_required import WorkspaceRuntimeNetworkRestrictionProxyRequired
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WORKSPACERUNTIMENETWORKRESTRICTION_ONE_OF_SCHEMAS = ["WorkspaceRuntimeNetworkRestrictionDirect", "WorkspaceRuntimeNetworkRestrictionInherit", "WorkspaceRuntimeNetworkRestrictionNoNetwork", "WorkspaceRuntimeNetworkRestrictionProxyRequired"]

class WorkspaceRuntimeNetworkRestriction(BaseModel):
    """
    WorkspaceRuntimeNetworkRestriction
    """
    # data type: WorkspaceRuntimeNetworkRestrictionInherit
    oneof_schema_1_validator: Optional[WorkspaceRuntimeNetworkRestrictionInherit] = None
    # data type: WorkspaceRuntimeNetworkRestrictionDirect
    oneof_schema_2_validator: Optional[WorkspaceRuntimeNetworkRestrictionDirect] = None
    # data type: WorkspaceRuntimeNetworkRestrictionProxyRequired
    oneof_schema_3_validator: Optional[WorkspaceRuntimeNetworkRestrictionProxyRequired] = None
    # data type: WorkspaceRuntimeNetworkRestrictionNoNetwork
    oneof_schema_4_validator: Optional[WorkspaceRuntimeNetworkRestrictionNoNetwork] = None
    actual_instance: Optional[Union[WorkspaceRuntimeNetworkRestrictionDirect, WorkspaceRuntimeNetworkRestrictionInherit, WorkspaceRuntimeNetworkRestrictionNoNetwork, WorkspaceRuntimeNetworkRestrictionProxyRequired]] = None
    one_of_schemas: Set[str] = { "WorkspaceRuntimeNetworkRestrictionDirect", "WorkspaceRuntimeNetworkRestrictionInherit", "WorkspaceRuntimeNetworkRestrictionNoNetwork", "WorkspaceRuntimeNetworkRestrictionProxyRequired" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WorkspaceRuntimeNetworkRestriction.model_construct()
        error_messages = []
        match = 0
        # validate data type: WorkspaceRuntimeNetworkRestrictionInherit
        if not isinstance(v, WorkspaceRuntimeNetworkRestrictionInherit):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceRuntimeNetworkRestrictionInherit`")
        else:
            match += 1
        # validate data type: WorkspaceRuntimeNetworkRestrictionDirect
        if not isinstance(v, WorkspaceRuntimeNetworkRestrictionDirect):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceRuntimeNetworkRestrictionDirect`")
        else:
            match += 1
        # validate data type: WorkspaceRuntimeNetworkRestrictionProxyRequired
        if not isinstance(v, WorkspaceRuntimeNetworkRestrictionProxyRequired):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceRuntimeNetworkRestrictionProxyRequired`")
        else:
            match += 1
        # validate data type: WorkspaceRuntimeNetworkRestrictionNoNetwork
        if not isinstance(v, WorkspaceRuntimeNetworkRestrictionNoNetwork):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceRuntimeNetworkRestrictionNoNetwork`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WorkspaceRuntimeNetworkRestriction with oneOf schemas: WorkspaceRuntimeNetworkRestrictionDirect, WorkspaceRuntimeNetworkRestrictionInherit, WorkspaceRuntimeNetworkRestrictionNoNetwork, WorkspaceRuntimeNetworkRestrictionProxyRequired. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WorkspaceRuntimeNetworkRestriction with oneOf schemas: WorkspaceRuntimeNetworkRestrictionDirect, WorkspaceRuntimeNetworkRestrictionInherit, WorkspaceRuntimeNetworkRestrictionNoNetwork, WorkspaceRuntimeNetworkRestrictionProxyRequired. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into WorkspaceRuntimeNetworkRestrictionInherit
        try:
            instance.actual_instance = WorkspaceRuntimeNetworkRestrictionInherit.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceRuntimeNetworkRestrictionDirect
        try:
            instance.actual_instance = WorkspaceRuntimeNetworkRestrictionDirect.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceRuntimeNetworkRestrictionProxyRequired
        try:
            instance.actual_instance = WorkspaceRuntimeNetworkRestrictionProxyRequired.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceRuntimeNetworkRestrictionNoNetwork
        try:
            instance.actual_instance = WorkspaceRuntimeNetworkRestrictionNoNetwork.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WorkspaceRuntimeNetworkRestriction with oneOf schemas: WorkspaceRuntimeNetworkRestrictionDirect, WorkspaceRuntimeNetworkRestrictionInherit, WorkspaceRuntimeNetworkRestrictionNoNetwork, WorkspaceRuntimeNetworkRestrictionProxyRequired. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WorkspaceRuntimeNetworkRestriction with oneOf schemas: WorkspaceRuntimeNetworkRestrictionDirect, WorkspaceRuntimeNetworkRestrictionInherit, WorkspaceRuntimeNetworkRestrictionNoNetwork, WorkspaceRuntimeNetworkRestrictionProxyRequired. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], WorkspaceRuntimeNetworkRestrictionDirect, WorkspaceRuntimeNetworkRestrictionInherit, WorkspaceRuntimeNetworkRestrictionNoNetwork, WorkspaceRuntimeNetworkRestrictionProxyRequired]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


