# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WorkspaceUploadFailure(str, Enum):
    """
    Workspace upload failure classification.
    """

    """
    allowed enum values
    """
    INVALID_REQUEST = 'invalid_request'
    AUTHORIZATION = 'authorization'
    TOO_LARGE = 'too_large'
    REVISION_CONFLICT = 'revision_conflict'
    DESTINATION_CONFLICT = 'destination_conflict'
    RUNTIME_UNAVAILABLE = 'runtime_unavailable'
    FENCED = 'fenced'
    INTEGRITY = 'integrity'
    TRANSFER = 'transfer'
    CANCELLED = 'cancelled'
    EXPIRED = 'expired'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkspaceUploadFailure from a JSON string"""
        return cls(json.loads(json_str))


