# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.applied_inference_profile import AppliedInferenceProfile

class TestAppliedInferenceProfile(unittest.TestCase):
    """AppliedInferenceProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppliedInferenceProfile:
        """Test AppliedInferenceProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppliedInferenceProfile`
        """
        model = AppliedInferenceProfile()
        if include_optional:
            return AppliedInferenceProfile(
                model_target_label = '0',
                reasoning_effort = 'none'
            )
        else:
            return AppliedInferenceProfile(
                model_target_label = '0',
                reasoning_effort = 'none',
        )
        """

    def testAppliedInferenceProfile(self):
        """Test AppliedInferenceProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
