# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_infrastructure_profile_spec import RuntimeInfrastructureProfileSpec

class TestRuntimeInfrastructureProfileSpec(unittest.TestCase):
    """RuntimeInfrastructureProfileSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeInfrastructureProfileSpec:
        """Test RuntimeInfrastructureProfileSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeInfrastructureProfileSpec`
        """
        model = RuntimeInfrastructureProfileSpec()
        if include_optional:
            return RuntimeInfrastructureProfileSpec(
                profile_kind = 'docker_container',
                contract_family = 'docker.container-profile',
                schema_version = 1,
                runner_resources = { },
                workspace_volume = { },
                network_policy = { },
                service_account_name = '',
                scheduling = { },
                dind = { },
                network_name = ''
            )
        else:
            return RuntimeInfrastructureProfileSpec(
                profile_kind = 'docker_container',
                contract_family = 'docker.container-profile',
                schema_version = 1,
                runner_resources = { },
                workspace_volume = { },
                network_policy = { },
                service_account_name = '',
                scheduling = { },
                dind = { },
                network_name = '',
        )
        """

    def testRuntimeInfrastructureProfileSpec(self):
        """Test RuntimeInfrastructureProfileSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
