# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.api.xaio_auth_v1_api import XAIOAuthV1Api


class TestXAIOAuthV1Api(unittest.TestCase):
    """XAIOAuthV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = XAIOAuthV1Api()

    def tearDown(self) -> None:
        pass

    def test_xai_oauth_v1_cancel_device(self) -> None:
        """Test case for xai_oauth_v1_cancel_device

        Cancel Device
        """
        pass

    def test_xai_oauth_v1_poll_device(self) -> None:
        """Test case for xai_oauth_v1_poll_device

        Poll Device
        """
        pass

    def test_xai_oauth_v1_start_device(self) -> None:
        """Test case for xai_oauth_v1_start_device

        Start Device
        """
        pass


if __name__ == '__main__':
    unittest.main()
