# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.api.external_channel_v1_api import ExternalChannelV1Api


class TestExternalChannelV1Api(unittest.TestCase):
    """ExternalChannelV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ExternalChannelV1Api()

    def tearDown(self) -> None:
        pass

    def test_external_channel_v1_decide_approval_request(self) -> None:
        """Test case for external_channel_v1_decide_approval_request

        Decide Approval Request
        """
        pass

    def test_external_channel_v1_disconnect_connection(self) -> None:
        """Test case for external_channel_v1_disconnect_connection

        Disconnect Connection
        """
        pass

    def test_external_channel_v1_disconnect_session_channel(self) -> None:
        """Test case for external_channel_v1_disconnect_session_channel

        Disconnect Session Channel
        """
        pass

    def test_external_channel_v1_get_approval_request(self) -> None:
        """Test case for external_channel_v1_get_approval_request

        Get Approval Request
        """
        pass

    def test_external_channel_v1_get_manifest_guidance(self) -> None:
        """Test case for external_channel_v1_get_manifest_guidance

        Get Manifest Guidance
        """
        pass

    def test_external_channel_v1_list_agent_access(self) -> None:
        """Test case for external_channel_v1_list_agent_access

        List Agent Access
        """
        pass

    def test_external_channel_v1_list_connections(self) -> None:
        """Test case for external_channel_v1_list_connections

        List Connections
        """
        pass

    def test_external_channel_v1_list_session_channels(self) -> None:
        """Test case for external_channel_v1_list_session_channels

        List Session Channels
        """
        pass

    def test_external_channel_v1_remove_access_block(self) -> None:
        """Test case for external_channel_v1_remove_access_block

        Remove Access Block
        """
        pass

    def test_external_channel_v1_revoke_access_grant(self) -> None:
        """Test case for external_channel_v1_revoke_access_grant

        Revoke Access Grant
        """
        pass

    def test_external_channel_v1_setup_slack_connection(self) -> None:
        """Test case for external_channel_v1_setup_slack_connection

        Setup Slack Connection
        """
        pass

    def test_external_channel_v1_update_slack_connection(self) -> None:
        """Test case for external_channel_v1_update_slack_connection

        Update Slack Connection
        """
        pass

    def test_external_channel_v1_validate_connection(self) -> None:
        """Test case for external_channel_v1_validate_connection

        Validate Connection
        """
        pass


if __name__ == '__main__':
    unittest.main()
