# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.account_link_list_response import AccountLinkListResponse

class TestAccountLinkListResponse(unittest.TestCase):
    """AccountLinkListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountLinkListResponse:
        """Test AccountLinkListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountLinkListResponse`
        """
        model = AccountLinkListResponse()
        if include_optional:
            return AccountLinkListResponse(
                items = [
                    azentspublicclient.models.account_link_response.AccountLinkResponse(
                        id = '', 
                        workspace_id = '', 
                        workspace_name = '', 
                        workspace_handle = '', 
                        provider = 'slack', 
                        identity_scope = '', 
                        provider_tenant_display_label = '', 
                        provider_display_label = '', 
                        linked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        state = 'active', )
                    ]
            )
        else:
            return AccountLinkListResponse(
                items = [
                    azentspublicclient.models.account_link_response.AccountLinkResponse(
                        id = '', 
                        workspace_id = '', 
                        workspace_name = '', 
                        workspace_handle = '', 
                        provider = 'slack', 
                        identity_scope = '', 
                        provider_tenant_display_label = '', 
                        provider_display_label = '', 
                        linked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        state = 'active', )
                    ],
        )
        """

    def testAccountLinkListResponse(self):
        """Test AccountLinkListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
