# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.automatic_session_projects_invalid_path_error_response import AutomaticSessionProjectsInvalidPathErrorResponse

class TestAutomaticSessionProjectsInvalidPathErrorResponse(unittest.TestCase):
    """AutomaticSessionProjectsInvalidPathErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutomaticSessionProjectsInvalidPathErrorResponse:
        """Test AutomaticSessionProjectsInvalidPathErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutomaticSessionProjectsInvalidPathErrorResponse`
        """
        model = AutomaticSessionProjectsInvalidPathErrorResponse()
        if include_optional:
            return AutomaticSessionProjectsInvalidPathErrorResponse(
                detail = azentspublicclient.models.automatic_session_projects_invalid_path_detail.AutomaticSessionProjectsInvalidPathDetail(
                    message = '', 
                    path = '', )
            )
        else:
            return AutomaticSessionProjectsInvalidPathErrorResponse(
                detail = azentspublicclient.models.automatic_session_projects_invalid_path_detail.AutomaticSessionProjectsInvalidPathDetail(
                    message = '', 
                    path = '', ),
        )
        """

    def testAutomaticSessionProjectsInvalidPathErrorResponse(self):
        """Test AutomaticSessionProjectsInvalidPathErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
