# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.todo_item_response import TodoItemResponse

class TestTodoItemResponse(unittest.TestCase):
    """TodoItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TodoItemResponse:
        """Test TodoItemResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TodoItemResponse`
        """
        model = TodoItemResponse()
        if include_optional:
            return TodoItemResponse(
                content = '',
                status = 'pending'
            )
        else:
            return TodoItemResponse(
                content = '',
                status = 'pending',
        )
        """

    def testTodoItemResponse(self):
        """Test TodoItemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
