# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.external_channel_multi_impact_binding import ExternalChannelMultiImpactBinding

class TestExternalChannelMultiImpactBinding(unittest.TestCase):
    """ExternalChannelMultiImpactBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalChannelMultiImpactBinding:
        """Test ExternalChannelMultiImpactBinding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalChannelMultiImpactBinding`
        """
        model = ExternalChannelMultiImpactBinding()
        if include_optional:
            return ExternalChannelMultiImpactBinding(
                id = '',
                route_id = '',
                agent_session_id = '',
                resource_id = '',
                channel_label = '',
                thread_label = ''
            )
        else:
            return ExternalChannelMultiImpactBinding(
                id = '',
                route_id = '',
                agent_session_id = '',
                resource_id = '',
                channel_label = '',
                thread_label = '',
        )
        """

    def testExternalChannelMultiImpactBinding(self):
        """Test ExternalChannelMultiImpactBinding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
