# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_execution_policy_restriction import RuntimeExecutionPolicyRestriction

class TestRuntimeExecutionPolicyRestriction(unittest.TestCase):
    """RuntimeExecutionPolicyRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeExecutionPolicyRestriction:
        """Test RuntimeExecutionPolicyRestriction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeExecutionPolicyRestriction`
        """
        model = RuntimeExecutionPolicyRestriction()
        if include_optional:
            return RuntimeExecutionPolicyRestriction(
                schema_version = 1,
                docker = { },
                resources = { }
            )
        else:
            return RuntimeExecutionPolicyRestriction(
                schema_version = 1,
                docker = { },
                resources = { },
        )
        """

    def testRuntimeExecutionPolicyRestriction(self):
        """Test RuntimeExecutionPolicyRestriction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
