# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.agent_workspace_entry_response import AgentWorkspaceEntryResponse

class TestAgentWorkspaceEntryResponse(unittest.TestCase):
    """AgentWorkspaceEntryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentWorkspaceEntryResponse:
        """Test AgentWorkspaceEntryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentWorkspaceEntryResponse`
        """
        model = AgentWorkspaceEntryResponse()
        if include_optional:
            return AgentWorkspaceEntryResponse(
                name = '',
                path = '',
                kind = 'file',
                size = 56,
                media_type = '',
                modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AgentWorkspaceEntryResponse(
                name = '',
                path = '',
                kind = 'file',
        )
        """

    def testAgentWorkspaceEntryResponse(self):
        """Test AgentWorkspaceEntryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
