# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.api.runtime_execution_v1_api import RuntimeExecutionV1Api


class TestRuntimeExecutionV1Api(unittest.TestCase):
    """RuntimeExecutionV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = RuntimeExecutionV1Api()

    def tearDown(self) -> None:
        pass

    def test_runtime_execution_v1_apply_agent_policy(self) -> None:
        """Test case for runtime_execution_v1_apply_agent_policy

        Apply Agent Policy
        """
        pass

    def test_runtime_execution_v1_get_agent_policy(self) -> None:
        """Test case for runtime_execution_v1_get_agent_policy

        Get Agent Policy
        """
        pass

    def test_runtime_execution_v1_get_workspace_policy(self) -> None:
        """Test case for runtime_execution_v1_get_workspace_policy

        Get Workspace Policy
        """
        pass

    def test_runtime_execution_v1_list_agent_audit_events(self) -> None:
        """Test case for runtime_execution_v1_list_agent_audit_events

        List Agent Audit Events
        """
        pass

    def test_runtime_execution_v1_list_workspace_audit_events(self) -> None:
        """Test case for runtime_execution_v1_list_workspace_audit_events

        List Workspace Audit Events
        """
        pass

    def test_runtime_execution_v1_list_workspace_profiles(self) -> None:
        """Test case for runtime_execution_v1_list_workspace_profiles

        List Workspace Profiles
        """
        pass

    def test_runtime_execution_v1_replace_agent_policy(self) -> None:
        """Test case for runtime_execution_v1_replace_agent_policy

        Replace Agent Policy
        """
        pass

    def test_runtime_execution_v1_replace_workspace_policy(self) -> None:
        """Test case for runtime_execution_v1_replace_workspace_policy

        Replace Workspace Policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
