# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.pending_mailbox_external_channel_presentation import PendingMailboxExternalChannelPresentation

class TestPendingMailboxExternalChannelPresentation(unittest.TestCase):
    """PendingMailboxExternalChannelPresentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PendingMailboxExternalChannelPresentation:
        """Test PendingMailboxExternalChannelPresentation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PendingMailboxExternalChannelPresentation`
        """
        model = PendingMailboxExternalChannelPresentation()
        if include_optional:
            return PendingMailboxExternalChannelPresentation(
                type = 'external_channel_message',
                provider = '',
                resource_label = '',
                resource_type = '',
                external_message_id = '',
                sender_display_name = '',
                author_type = '',
                authorization = 'context_only',
                body = '',
                original_url = ''
            )
        else:
            return PendingMailboxExternalChannelPresentation(
                type = 'external_channel_message',
                provider = '',
                resource_label = '',
                resource_type = '',
                external_message_id = '',
                sender_display_name = '',
                author_type = '',
                authorization = 'context_only',
                body = '',
                original_url = '',
        )
        """

    def testPendingMailboxExternalChannelPresentation(self):
        """Test PendingMailboxExternalChannelPresentation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
