# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_web_close_request import RuntimeWebCloseRequest

class TestRuntimeWebCloseRequest(unittest.TestCase):
    """RuntimeWebCloseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeWebCloseRequest:
        """Test RuntimeWebCloseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeWebCloseRequest`
        """
        model = RuntimeWebCloseRequest()
        if include_optional:
            return RuntimeWebCloseRequest(
                expected_endpoint_revision = 0.0,
                operation_key = '0'
            )
        else:
            return RuntimeWebCloseRequest(
                expected_endpoint_revision = 0.0,
                operation_key = '0',
        )
        """

    def testRuntimeWebCloseRequest(self):
        """Test RuntimeWebCloseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
