# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.chat_live_run_state_response import ChatLiveRunStateResponse

class TestChatLiveRunStateResponse(unittest.TestCase):
    """ChatLiveRunStateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatLiveRunStateResponse:
        """Test ChatLiveRunStateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatLiveRunStateResponse`
        """
        model = ChatLiveRunStateResponse()
        if include_optional:
            return ChatLiveRunStateResponse(
                run_id = '',
                phase = 'idle',
                status = 'pending',
                inference_profile = { },
                model_call_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                operation = azentspublicclient.models.chat_live_run_operation_response.ChatLiveRunOperationResponse(
                    kind = 'preparing_context', 
                    operation_id = '', 
                    status = 'running', ),
                retry = azentspublicclient.models.chat_live_run_retry_state_response.ChatLiveRunRetryStateResponse(
                    error_kind = 'model_provider', 
                    status = '', 
                    last_error_message = '', 
                    failed_attempt_count = 56, 
                    max_retries = 56, 
                    backoff_seconds = 56, 
                    next_retry_at = '', 
                    attempts = [
                        azentspublicclient.models.chat_live_run_retry_attempt_response.ChatLiveRunRetryAttemptResponse(
                            attempt_number = 56, 
                            user_message = '', 
                            error_type = '', 
                            source = '', 
                            failed_at = '', 
                            backoff_seconds = 56, 
                            next_retry_at = '', 
                            retryability = '', 
                            failure_code = '', 
                            truncated = True, )
                        ], )
            )
        else:
            return ChatLiveRunStateResponse(
                run_id = '',
                phase = 'idle',
                status = 'pending',
                inference_profile = { },
                model_call_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testChatLiveRunStateResponse(self):
        """Test ChatLiveRunStateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
