# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.agent_workspace_bulk_move_response import AgentWorkspaceBulkMoveResponse

class TestAgentWorkspaceBulkMoveResponse(unittest.TestCase):
    """AgentWorkspaceBulkMoveResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentWorkspaceBulkMoveResponse:
        """Test AgentWorkspaceBulkMoveResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentWorkspaceBulkMoveResponse`
        """
        model = AgentWorkspaceBulkMoveResponse()
        if include_optional:
            return AgentWorkspaceBulkMoveResponse(
                entries = [
                    azentspublicclient.models.agent_workspace_move_response.AgentWorkspaceMoveResponse(
                        source_path = '', 
                        destination_path = '', )
                    ]
            )
        else:
            return AgentWorkspaceBulkMoveResponse(
                entries = [
                    azentspublicclient.models.agent_workspace_move_response.AgentWorkspaceMoveResponse(
                        source_path = '', 
                        destination_path = '', )
                    ],
        )
        """

    def testAgentWorkspaceBulkMoveResponse(self):
        """Test AgentWorkspaceBulkMoveResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
