# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.llm_provider_integration_create_request_config import LLMProviderIntegrationCreateRequestConfig

class TestLLMProviderIntegrationCreateRequestConfig(unittest.TestCase):
    """LLMProviderIntegrationCreateRequestConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMProviderIntegrationCreateRequestConfig:
        """Test LLMProviderIntegrationCreateRequestConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMProviderIntegrationCreateRequestConfig`
        """
        model = LLMProviderIntegrationCreateRequestConfig()
        if include_optional:
            return LLMProviderIntegrationCreateRequestConfig(
                type = 'aws_credentials',
                access_key_id = '',
                region = '',
                role_arn = '',
                project_id = ''
            )
        else:
            return LLMProviderIntegrationCreateRequestConfig(
                access_key_id = '',
                region = '',
                project_id = '',
        )
        """

    def testLLMProviderIntegrationCreateRequestConfig(self):
        """Test LLMProviderIntegrationCreateRequestConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
