# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.chat_live_run_retry_attempt_response import ChatLiveRunRetryAttemptResponse

class TestChatLiveRunRetryAttemptResponse(unittest.TestCase):
    """ChatLiveRunRetryAttemptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatLiveRunRetryAttemptResponse:
        """Test ChatLiveRunRetryAttemptResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatLiveRunRetryAttemptResponse`
        """
        model = ChatLiveRunRetryAttemptResponse()
        if include_optional:
            return ChatLiveRunRetryAttemptResponse(
                attempt_number = 56,
                user_message = '',
                error_type = '',
                source = '',
                failed_at = '',
                backoff_seconds = 56,
                next_retry_at = '',
                retryability = '',
                failure_code = '',
                truncated = True
            )
        else:
            return ChatLiveRunRetryAttemptResponse(
                attempt_number = 56,
                user_message = '',
                error_type = '',
                source = '',
                failed_at = '',
                backoff_seconds = 56,
                next_retry_at = '',
                retryability = '',
                truncated = True,
        )
        """

    def testChatLiveRunRetryAttemptResponse(self):
        """Test ChatLiveRunRetryAttemptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
