# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.memory_update_request import MemoryUpdateRequest

class TestMemoryUpdateRequest(unittest.TestCase):
    """MemoryUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemoryUpdateRequest:
        """Test MemoryUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemoryUpdateRequest`
        """
        model = MemoryUpdateRequest()
        if include_optional:
            return MemoryUpdateRequest(
                type = '0',
                name = '0',
                description = '0',
                content = '0'
            )
        else:
            return MemoryUpdateRequest(
        )
        """

    def testMemoryUpdateRequest(self):
        """Test MemoryUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
