# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.api.auth_v1_api import AuthV1Api


class TestAuthV1Api(unittest.TestCase):
    """AuthV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthV1Api()

    def tearDown(self) -> None:
        pass

    def test_auth_v1_get_login_methods(self) -> None:
        """Test case for auth_v1_get_login_methods

        Get Login Methods
        """
        pass

    def test_auth_v1_get_signup_status(self) -> None:
        """Test case for auth_v1_get_signup_status

        Get Signup Status
        """
        pass

    def test_auth_v1_login_with_password(self) -> None:
        """Test case for auth_v1_login_with_password

        Login With Password
        """
        pass

    def test_auth_v1_logout(self) -> None:
        """Test case for auth_v1_logout

        Logout
        """
        pass

    def test_auth_v1_preview_password_reset_token(self) -> None:
        """Test case for auth_v1_preview_password_reset_token

        Preview Password Reset Token
        """
        pass

    def test_auth_v1_preview_signup_token(self) -> None:
        """Test case for auth_v1_preview_signup_token

        Preview Signup Token
        """
        pass

    def test_auth_v1_redeem_password_reset_token(self) -> None:
        """Test case for auth_v1_redeem_password_reset_token

        Redeem Password Reset Token
        """
        pass

    def test_auth_v1_redeem_signup_token(self) -> None:
        """Test case for auth_v1_redeem_signup_token

        Redeem Signup Token
        """
        pass

    def test_auth_v1_refresh_token(self) -> None:
        """Test case for auth_v1_refresh_token

        Refresh Token
        """
        pass

    def test_auth_v1_request_signup_email(self) -> None:
        """Test case for auth_v1_request_signup_email

        Request Signup Email
        """
        pass

    def test_auth_v1_send_code(self) -> None:
        """Test case for auth_v1_send_code

        Send Code
        """
        pass

    def test_auth_v1_verify_code(self) -> None:
        """Test case for auth_v1_verify_code

        Verify Code
        """
        pass


if __name__ == '__main__':
    unittest.main()
