# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.historical_memory_list_response import HistoricalMemoryListResponse

class TestHistoricalMemoryListResponse(unittest.TestCase):
    """HistoricalMemoryListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoricalMemoryListResponse:
        """Test HistoricalMemoryListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoricalMemoryListResponse`
        """
        model = HistoricalMemoryListResponse()
        if include_optional:
            return HistoricalMemoryListResponse(
                items = [
                    azentspublicclient.models.historical_memory_response.HistoricalMemoryResponse(
                        source_session_id = '', 
                        scope = 'team', 
                        source_title = '', 
                        source_activity_through = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        prepared_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        summary = '', 
                        source_path = '', )
                    ],
                next_cursor = ''
            )
        else:
            return HistoricalMemoryListResponse(
                items = [
                    azentspublicclient.models.historical_memory_response.HistoricalMemoryResponse(
                        source_session_id = '', 
                        scope = 'team', 
                        source_title = '', 
                        source_activity_through = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        prepared_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        summary = '', 
                        source_path = '', )
                    ],
                next_cursor = '',
        )
        """

    def testHistoricalMemoryListResponse(self):
        """Test HistoricalMemoryListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
