# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.invitation_list_response import InvitationListResponse

class TestInvitationListResponse(unittest.TestCase):
    """InvitationListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvitationListResponse:
        """Test InvitationListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvitationListResponse`
        """
        model = InvitationListResponse()
        if include_optional:
            return InvitationListResponse(
                items = [
                    azentspublicclient.models.invitation_response.InvitationResponse(
                        id = '', 
                        workspace_id = '', 
                        email = '', 
                        role = 'owner', 
                        invited_by = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return InvitationListResponse(
                items = [
                    azentspublicclient.models.invitation_response.InvitationResponse(
                        id = '', 
                        workspace_id = '', 
                        email = '', 
                        role = 'owner', 
                        invited_by = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testInvitationListResponse(self):
        """Test InvitationListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
