# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.model_modality import ModelModality

class TestModelModality(unittest.TestCase):
    """ModelModality unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelModality(self):
        """Test ModelModality"""
        # inst = ModelModality()

if __name__ == '__main__':
    unittest.main()
