# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.ws_ticket_response import WsTicketResponse

class TestWsTicketResponse(unittest.TestCase):
    """WsTicketResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WsTicketResponse:
        """Test WsTicketResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WsTicketResponse`
        """
        model = WsTicketResponse()
        if include_optional:
            return WsTicketResponse(
                ticket = ''
            )
        else:
            return WsTicketResponse(
                ticket = '',
        )
        """

    def testWsTicketResponse(self):
        """Test WsTicketResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
