# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.managed_binding_list_response import ManagedBindingListResponse

class TestManagedBindingListResponse(unittest.TestCase):
    """ManagedBindingListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedBindingListResponse:
        """Test ManagedBindingListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedBindingListResponse`
        """
        model = ManagedBindingListResponse()
        if include_optional:
            return ManagedBindingListResponse(
                items = [
                    azentspublicclient.models.managed_binding.ManagedBinding(
                        id = '', 
                        agent_session_id = '', 
                        provider = 'slack', 
                        response_mode = 'mention_only', 
                        resource_type = 'parent_channel', 
                        conversation_location = 'channel', 
                        resource_label = '', 
                        connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        disconnected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        disconnect_reason = '', 
                        latest_activity_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        work = azentspublicclient.models.managed_work.ManagedWork(
                            id = '', 
                            status = 'active', 
                            title = '', 
                            tasks = [
                                azentspublicclient.models.managed_work_task.ManagedWorkTask(
                                    id = '', 
                                    title = '', 
                                    status = 'pending', 
                                    details = '', 
                                    output = '', 
                                    sources = [
                                        azentspublicclient.models.managed_work_source.ManagedWorkSource(
                                            url = '', 
                                            label = '', )
                                        ], )
                                ], 
                            state_revision = 56, 
                            desired_progress_revision = 56, 
                            progress_projected = True, 
                            projection_state = 'synchronized', 
                            finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ],
                grants = [
                    azentspublicclient.models.managed_grant.ManagedGrant(
                        id = '', 
                        agent_id = '', 
                        principal_id = '', 
                        principal_label = '', 
                        principal_provider_user_id = '', 
                        scope = 'session', 
                        agent_session_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ManagedBindingListResponse(
                items = [
                    azentspublicclient.models.managed_binding.ManagedBinding(
                        id = '', 
                        agent_session_id = '', 
                        provider = 'slack', 
                        response_mode = 'mention_only', 
                        resource_type = 'parent_channel', 
                        conversation_location = 'channel', 
                        resource_label = '', 
                        connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        disconnected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        disconnect_reason = '', 
                        latest_activity_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        work = azentspublicclient.models.managed_work.ManagedWork(
                            id = '', 
                            status = 'active', 
                            title = '', 
                            tasks = [
                                azentspublicclient.models.managed_work_task.ManagedWorkTask(
                                    id = '', 
                                    title = '', 
                                    status = 'pending', 
                                    details = '', 
                                    output = '', 
                                    sources = [
                                        azentspublicclient.models.managed_work_source.ManagedWorkSource(
                                            url = '', 
                                            label = '', )
                                        ], )
                                ], 
                            state_revision = 56, 
                            desired_progress_revision = 56, 
                            progress_projected = True, 
                            projection_state = 'synchronized', 
                            finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ],
                grants = [
                    azentspublicclient.models.managed_grant.ManagedGrant(
                        id = '', 
                        agent_id = '', 
                        principal_id = '', 
                        principal_label = '', 
                        principal_provider_user_id = '', 
                        scope = 'session', 
                        agent_session_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testManagedBindingListResponse(self):
        """Test ManagedBindingListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
