# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.catalog_time_window import CatalogTimeWindow

class TestCatalogTimeWindow(unittest.TestCase):
    """CatalogTimeWindow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogTimeWindow:
        """Test CatalogTimeWindow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogTimeWindow`
        """
        model = CatalogTimeWindow()
        if include_optional:
            return CatalogTimeWindow(
                start_minute = 56,
                end_minute = 56,
                weekdays = [
                    56
                    ]
            )
        else:
            return CatalogTimeWindow(
                start_minute = 56,
                end_minute = 56,
                weekdays = [
                    56
                    ],
        )
        """

    def testCatalogTimeWindow(self):
        """Test CatalogTimeWindow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
