# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.api.security_v1_api import SecurityV1Api


class TestSecurityV1Api(unittest.TestCase):
    """SecurityV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityV1Api()

    def tearDown(self) -> None:
        pass

    def test_security_v1_elevate_with_email(self) -> None:
        """Test case for security_v1_elevate_with_email

        Elevate With Email
        """
        pass

    def test_security_v1_elevate_with_password(self) -> None:
        """Test case for security_v1_elevate_with_password

        Elevate With Password
        """
        pass

    def test_security_v1_get_auth_methods(self) -> None:
        """Test case for security_v1_get_auth_methods

        Get Auth Methods
        """
        pass

    def test_security_v1_get_elevation_methods(self) -> None:
        """Test case for security_v1_get_elevation_methods

        Get Elevation Methods
        """
        pass

    def test_security_v1_remove_password(self) -> None:
        """Test case for security_v1_remove_password

        Remove Password
        """
        pass

    def test_security_v1_send_elevation_code(self) -> None:
        """Test case for security_v1_send_elevation_code

        Send Elevation Code
        """
        pass

    def test_security_v1_set_password(self) -> None:
        """Test case for security_v1_set_password

        Set Password
        """
        pass


if __name__ == '__main__':
    unittest.main()
