# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.model_catalog_entry_response import ModelCatalogEntryResponse

class TestModelCatalogEntryResponse(unittest.TestCase):
    """ModelCatalogEntryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelCatalogEntryResponse:
        """Test ModelCatalogEntryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelCatalogEntryResponse`
        """
        model = ModelCatalogEntryResponse()
        if include_optional:
            return ModelCatalogEntryResponse(
                id = '',
                provider = 'openai',
                provider_model_identifier = '',
                runtime_model_identifier = '',
                display_name = '',
                normalized_capabilities = azentspublicclient.models.model_capabilities.ModelCapabilities(
                    context_window = azentspublicclient.models.model_context_window.ModelContextWindow(
                        max_input_tokens = 1.0, 
                        max_output_tokens = 1.0, ), 
                    modalities = azentspublicclient.models.model_modalities.ModelModalities(
                        input = [
                            'text'
                            ], 
                        output = [
                            'text'
                            ], ), 
                    tool_calling = azentspublicclient.models.model_tool_calling_capabilities.ModelToolCallingCapabilities(
                        supported = True, 
                        parallel_tool_calls = True, 
                        strict_json_schema = True, ), 
                    reasoning = azentspublicclient.models.model_reasoning_capabilities.ModelReasoningCapabilities(
                        supported = True, 
                        effort_levels = [
                            'none'
                            ], 
                        summaries = True, ), 
                    built_in_tools = azentspublicclient.models.model_built_in_tool_capabilities.ModelBuiltInToolCapabilities(
                        supported = [
                            ''
                            ], ), 
                    parameters = azentspublicclient.models.model_parameter_capabilities.ModelParameterCapabilities(
                        temperature = True, 
                        max_output_tokens = True, 
                        top_p = True, 
                        top_k = True, 
                        stop_sequences = True, ), 
                    compatibility = azentspublicclient.models.model_compatibility_capabilities.ModelCompatibilityCapabilities(
                        provider_family = '', 
                        responses_api = True, 
                        responses_lite = True, 
                        unsupported_media_policy = 'text_substitution', ), ),
                lifecycle_status = '',
                visibility_status = '',
                publisher = '',
                family = '',
                source_metadata = { },
                projection_metadata = { }
            )
        else:
            return ModelCatalogEntryResponse(
                id = '',
                provider = 'openai',
                provider_model_identifier = '',
                runtime_model_identifier = '',
                display_name = '',
                normalized_capabilities = azentspublicclient.models.model_capabilities.ModelCapabilities(
                    context_window = azentspublicclient.models.model_context_window.ModelContextWindow(
                        max_input_tokens = 1.0, 
                        max_output_tokens = 1.0, ), 
                    modalities = azentspublicclient.models.model_modalities.ModelModalities(
                        input = [
                            'text'
                            ], 
                        output = [
                            'text'
                            ], ), 
                    tool_calling = azentspublicclient.models.model_tool_calling_capabilities.ModelToolCallingCapabilities(
                        supported = True, 
                        parallel_tool_calls = True, 
                        strict_json_schema = True, ), 
                    reasoning = azentspublicclient.models.model_reasoning_capabilities.ModelReasoningCapabilities(
                        supported = True, 
                        effort_levels = [
                            'none'
                            ], 
                        summaries = True, ), 
                    built_in_tools = azentspublicclient.models.model_built_in_tool_capabilities.ModelBuiltInToolCapabilities(
                        supported = [
                            ''
                            ], ), 
                    parameters = azentspublicclient.models.model_parameter_capabilities.ModelParameterCapabilities(
                        temperature = True, 
                        max_output_tokens = True, 
                        top_p = True, 
                        top_k = True, 
                        stop_sequences = True, ), 
                    compatibility = azentspublicclient.models.model_compatibility_capabilities.ModelCompatibilityCapabilities(
                        provider_family = '', 
                        responses_api = True, 
                        responses_lite = True, 
                        unsupported_media_policy = 'text_substitution', ), ),
                lifecycle_status = '',
                visibility_status = '',
                publisher = '',
                family = '',
                source_metadata = { },
                projection_metadata = { },
        )
        """

    def testModelCatalogEntryResponse(self):
        """Test ModelCatalogEntryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
