# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.get_auth_methods_response import GetAuthMethodsResponse

class TestGetAuthMethodsResponse(unittest.TestCase):
    """GetAuthMethodsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAuthMethodsResponse:
        """Test GetAuthMethodsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAuthMethodsResponse`
        """
        model = GetAuthMethodsResponse()
        if include_optional:
            return GetAuthMethodsResponse(
                methods = [
                    azentspublicclient.models.auth_method.AuthMethod(
                        type = '',
                        enabled = True,
                        configured = True,
                        valid = True,
                        can_login = True,
                        can_elevate = True,
                        can_remove = True,
                        unavailable_reason = '', )
                    ]
            )
        else:
            return GetAuthMethodsResponse(
                methods = [
                    azentspublicclient.models.auth_method.AuthMethod(
                        type = '',
                        enabled = True,
                        configured = True,
                        valid = True,
                        can_login = True,
                        can_elevate = True,
                        can_remove = True,
                        unavailable_reason = '', )
                    ],
        )
        """

    def testGetAuthMethodsResponse(self):
        """Test GetAuthMethodsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
