# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.agent_toolkit_attach_request import AgentToolkitAttachRequest

class TestAgentToolkitAttachRequest(unittest.TestCase):
    """AgentToolkitAttachRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentToolkitAttachRequest:
        """Test AgentToolkitAttachRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentToolkitAttachRequest`
        """
        model = AgentToolkitAttachRequest()
        if include_optional:
            return AgentToolkitAttachRequest(
                toolkit_id = ''
            )
        else:
            return AgentToolkitAttachRequest(
                toolkit_id = '',
        )
        """

    def testAgentToolkitAttachRequest(self):
        """Test AgentToolkitAttachRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
