# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.agent_runtime_summary_response import AgentRuntimeSummaryResponse

class TestAgentRuntimeSummaryResponse(unittest.TestCase):
    """AgentRuntimeSummaryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentRuntimeSummaryResponse:
        """Test AgentRuntimeSummaryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentRuntimeSummaryResponse`
        """
        model = AgentRuntimeSummaryResponse()
        if include_optional:
            return AgentRuntimeSummaryResponse(
                summary = 'stopped',
                actions = azentspublicclient.models.agent_runtime_actions_response.AgentRuntimeActionsResponse(
                    start = True, 
                    stop = True, 
                    restart = True, 
                    reset = True, 
                    use_runner = True, ),
                failure = azentspublicclient.models.agent_runtime_failure_response.AgentRuntimeFailureResponse(
                    generation = 56, 
                    code = '', 
                    message = '', )
            )
        else:
            return AgentRuntimeSummaryResponse(
                summary = 'stopped',
                actions = azentspublicclient.models.agent_runtime_actions_response.AgentRuntimeActionsResponse(
                    start = True, 
                    stop = True, 
                    restart = True, 
                    reset = True, 
                    use_runner = True, ),
                failure = azentspublicclient.models.agent_runtime_failure_response.AgentRuntimeFailureResponse(
                    generation = 56, 
                    code = '', 
                    message = '', ),
        )
        """

    def testAgentRuntimeSummaryResponse(self):
        """Test AgentRuntimeSummaryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
