# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.docker_container_resources import DockerContainerResources

class TestDockerContainerResources(unittest.TestCase):
    """DockerContainerResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DockerContainerResources:
        """Test DockerContainerResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DockerContainerResources`
        """
        model = DockerContainerResources()
        if include_optional:
            return DockerContainerResources(
                cpu_reservation_millicores = 1.0,
                cpu_limit_millicores = 1.0,
                memory_reservation_bytes = 1.0,
                memory_limit_bytes = 1.0
            )
        else:
            return DockerContainerResources(
                cpu_reservation_millicores = 1.0,
                cpu_limit_millicores = 1.0,
                memory_reservation_bytes = 1.0,
                memory_limit_bytes = 1.0,
        )
        """

    def testDockerContainerResources(self):
        """Test DockerContainerResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
