# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.model_catalog_sync_attempt_response import ModelCatalogSyncAttemptResponse

class TestModelCatalogSyncAttemptResponse(unittest.TestCase):
    """ModelCatalogSyncAttemptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelCatalogSyncAttemptResponse:
        """Test ModelCatalogSyncAttemptResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelCatalogSyncAttemptResponse`
        """
        model = ModelCatalogSyncAttemptResponse()
        if include_optional:
            return ModelCatalogSyncAttemptResponse(
                id = '',
                status = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                failure_code = '',
                failure_message = '',
                action_hint = '',
                fetched_count = 56,
                matched_count = 56,
                skipped_count = 56,
                hidden_count = 56
            )
        else:
            return ModelCatalogSyncAttemptResponse(
                id = '',
                status = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                failure_code = '',
                failure_message = '',
                action_hint = '',
                fetched_count = 56,
                matched_count = 56,
                skipped_count = 56,
                hidden_count = 56,
        )
        """

    def testModelCatalogSyncAttemptResponse(self):
        """Test ModelCatalogSyncAttemptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
