# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.external_channel_binding_status import ExternalChannelBindingStatus

class TestExternalChannelBindingStatus(unittest.TestCase):
    """ExternalChannelBindingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalChannelBindingStatus(self):
        """Test ExternalChannelBindingStatus"""
        # inst = ExternalChannelBindingStatus()

if __name__ == '__main__':
    unittest.main()
