# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.kubernetes_pod_profile_spec_v2 import KubernetesPodProfileSpecV2

class TestKubernetesPodProfileSpecV2(unittest.TestCase):
    """KubernetesPodProfileSpecV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KubernetesPodProfileSpecV2:
        """Test KubernetesPodProfileSpecV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KubernetesPodProfileSpecV2`
        """
        model = KubernetesPodProfileSpecV2()
        if include_optional:
            return KubernetesPodProfileSpecV2(
                profile_kind = 'kubernetes_pod',
                contract_family = 'kubernetes.pod-profile',
                schema_version = 2,
                runner_resources = azentspublicclient.models.kubernetes_container_resources.KubernetesContainerResources(
                    cpu_request_millicores = 1.0, 
                    cpu_limit_millicores = 1.0, 
                    memory_request_bytes = 1.0, 
                    memory_limit_bytes = 1.0, ),
                workspace_volume = azentspublicclient.models.kubernetes_workspace_volume.KubernetesWorkspaceVolume(
                    storage_class_name = '0', 
                    storage_request_bytes = 1.0, ),
                network_policy = azentspublicclient.models.runtime_network_policy_module.RuntimeNetworkPolicyModule(
                    allowed_cidrs = [
                        ''
                        ], 
                    denied_cidrs = [
                        ''
                        ], ),
                service_account_name = '',
                scheduling = azentspublicclient.models.kubernetes_scheduling_module.KubernetesSchedulingModule(
                    node_selector = {
                        'key' : ''
                        }, 
                    tolerations = [
                        azentspublicclient.models.kubernetes_toleration.KubernetesToleration(
                            key = '0', 
                            operator = 'Equal', 
                            value = '', 
                            effect = 'NoSchedule', 
                            toleration_seconds = 0.0, )
                        ], ),
                dind = azentspublicclient.models.kubernetes_din_d_module.KubernetesDinDModule(
                    engine_resources = azentspublicclient.models.kubernetes_container_resources.KubernetesContainerResources(
                        cpu_request_millicores = 1.0, 
                        cpu_limit_millicores = 1.0, 
                        memory_request_bytes = 1.0, 
                        memory_limit_bytes = 1.0, ), 
                    docker_storage_bytes = 1.0, 
                    shared_temporary_storage_bytes = 1.0, )
            )
        else:
            return KubernetesPodProfileSpecV2(
                profile_kind = 'kubernetes_pod',
                contract_family = 'kubernetes.pod-profile',
                schema_version = 2,
                runner_resources = azentspublicclient.models.kubernetes_container_resources.KubernetesContainerResources(
                    cpu_request_millicores = 1.0, 
                    cpu_limit_millicores = 1.0, 
                    memory_request_bytes = 1.0, 
                    memory_limit_bytes = 1.0, ),
                workspace_volume = azentspublicclient.models.kubernetes_workspace_volume.KubernetesWorkspaceVolume(
                    storage_class_name = '0', 
                    storage_request_bytes = 1.0, ),
                network_policy = azentspublicclient.models.runtime_network_policy_module.RuntimeNetworkPolicyModule(
                    allowed_cidrs = [
                        ''
                        ], 
                    denied_cidrs = [
                        ''
                        ], ),
                service_account_name = '',
                scheduling = azentspublicclient.models.kubernetes_scheduling_module.KubernetesSchedulingModule(
                    node_selector = {
                        'key' : ''
                        }, 
                    tolerations = [
                        azentspublicclient.models.kubernetes_toleration.KubernetesToleration(
                            key = '0', 
                            operator = 'Equal', 
                            value = '', 
                            effect = 'NoSchedule', 
                            toleration_seconds = 0.0, )
                        ], ),
                dind = azentspublicclient.models.kubernetes_din_d_module.KubernetesDinDModule(
                    engine_resources = azentspublicclient.models.kubernetes_container_resources.KubernetesContainerResources(
                        cpu_request_millicores = 1.0, 
                        cpu_limit_millicores = 1.0, 
                        memory_request_bytes = 1.0, 
                        memory_limit_bytes = 1.0, ), 
                    docker_storage_bytes = 1.0, 
                    shared_temporary_storage_bytes = 1.0, ),
        )
        """

    def testKubernetesPodProfileSpecV2(self):
        """Test KubernetesPodProfileSpecV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
