# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_containment_status import RuntimeContainmentStatus

class TestRuntimeContainmentStatus(unittest.TestCase):
    """RuntimeContainmentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeContainmentStatus:
        """Test RuntimeContainmentStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeContainmentStatus`
        """
        model = RuntimeContainmentStatus()
        if include_optional:
            return RuntimeContainmentStatus(
                enabled = True,
                applied = True,
                recreation_required = True,
                nested_docker_available = True,
                runtime_available = True,
                availability_reason_code = ''
            )
        else:
            return RuntimeContainmentStatus(
                enabled = True,
                applied = True,
                recreation_required = True,
                nested_docker_available = True,
                runtime_available = True,
                availability_reason_code = '',
        )
        """

    def testRuntimeContainmentStatus(self):
        """Test RuntimeContainmentStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
