# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_web_request_response import RuntimeWebRequestResponse

class TestRuntimeWebRequestResponse(unittest.TestCase):
    """RuntimeWebRequestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeWebRequestResponse:
        """Test RuntimeWebRequestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeWebRequestResponse`
        """
        model = RuntimeWebRequestResponse()
        if include_optional:
            return RuntimeWebRequestResponse(
                id = '',
                requester_kind = 'user',
                state = 'pending',
                revision = 1.0,
                label = '',
                decided_by_user_id = '',
                decided_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return RuntimeWebRequestResponse(
                id = '',
                requester_kind = 'user',
                state = 'pending',
                revision = 1.0,
                label = '',
                decided_by_user_id = '',
                decided_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testRuntimeWebRequestResponse(self):
        """Test RuntimeWebRequestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
