# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.scheduled_task_create_request import ScheduledTaskCreateRequest

class TestScheduledTaskCreateRequest(unittest.TestCase):
    """ScheduledTaskCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledTaskCreateRequest:
        """Test ScheduledTaskCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledTaskCreateRequest`
        """
        model = ScheduledTaskCreateRequest()
        if include_optional:
            return ScheduledTaskCreateRequest(
                session_id = '012345678910111213141516171819202122232425262728293031',
                title = '0',
                objective = '0',
                at = '',
                cron = '',
                timezone = '',
                channel_id = '0'
            )
        else:
            return ScheduledTaskCreateRequest(
                session_id = '012345678910111213141516171819202122232425262728293031',
                title = '0',
                objective = '0',
                at = '',
                cron = '',
                timezone = '',
                channel_id = '0',
        )
        """

    def testScheduledTaskCreateRequest(self):
        """Test ScheduledTaskCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
