# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.llm_provider_integration_response_config import LLMProviderIntegrationResponseConfig

class TestLLMProviderIntegrationResponseConfig(unittest.TestCase):
    """LLMProviderIntegrationResponseConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMProviderIntegrationResponseConfig:
        """Test LLMProviderIntegrationResponseConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMProviderIntegrationResponseConfig`
        """
        model = LLMProviderIntegrationResponseConfig()
        if include_optional:
            return LLMProviderIntegrationResponseConfig(
                type = 'aws_credentials',
                access_key_id = '',
                region = '',
                role_arn = '',
                project_id = '',
                account_id = '',
                email = '',
                plan_type = '',
                connection_method = 'device',
                status = 'connected',
                connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_refreshed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_failed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_failure_reason = '',
                entitlement_status = 'denied'
            )
        else:
            return LLMProviderIntegrationResponseConfig(
                access_key_id = '',
                region = '',
                project_id = '',
                connection_method = 'device',
                status = 'connected',
                connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_refreshed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_failed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_failure_reason = '',
        )
        """

    def testLLMProviderIntegrationResponseConfig(self):
        """Test LLMProviderIntegrationResponseConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
