# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_execution_resource_restriction import RuntimeExecutionResourceRestriction

class TestRuntimeExecutionResourceRestriction(unittest.TestCase):
    """RuntimeExecutionResourceRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeExecutionResourceRestriction:
        """Test RuntimeExecutionResourceRestriction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeExecutionResourceRestriction`
        """
        model = RuntimeExecutionResourceRestriction()
        if include_optional:
            return RuntimeExecutionResourceRestriction(
                cpu_millicores = 1.0,
                memory_bytes = 1.0,
                pids = 1.0,
                container_count = 1.0,
                ephemeral_storage_bytes = 1.0
            )
        else:
            return RuntimeExecutionResourceRestriction(
                cpu_millicores = 1.0,
                memory_bytes = 1.0,
                pids = 1.0,
                container_count = 1.0,
                ephemeral_storage_bytes = 1.0,
        )
        """

    def testRuntimeExecutionResourceRestriction(self):
        """Test RuntimeExecutionResourceRestriction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
