# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.update_workspace_user_role_request import UpdateWorkspaceUserRoleRequest

class TestUpdateWorkspaceUserRoleRequest(unittest.TestCase):
    """UpdateWorkspaceUserRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkspaceUserRoleRequest:
        """Test UpdateWorkspaceUserRoleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkspaceUserRoleRequest`
        """
        model = UpdateWorkspaceUserRoleRequest()
        if include_optional:
            return UpdateWorkspaceUserRoleRequest(
                role = 'owner'
            )
        else:
            return UpdateWorkspaceUserRoleRequest(
                role = 'owner',
        )
        """

    def testUpdateWorkspaceUserRoleRequest(self):
        """Test UpdateWorkspaceUserRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
