# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.managed_channel_default_list_response import ManagedChannelDefaultListResponse

class TestManagedChannelDefaultListResponse(unittest.TestCase):
    """ManagedChannelDefaultListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedChannelDefaultListResponse:
        """Test ManagedChannelDefaultListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedChannelDefaultListResponse`
        """
        model = ManagedChannelDefaultListResponse()
        if include_optional:
            return ManagedChannelDefaultListResponse(
                items = [
                    azentspublicclient.models.managed_channel_default.ManagedChannelDefault(
                        id = '', 
                        provider_channel_id = '', 
                        route_id = '', 
                        agent_id = '', 
                        agent_name = '', 
                        status = 'active', 
                        configured_by_user_id = '', 
                        invalidated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invalidation_reason = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ManagedChannelDefaultListResponse(
                items = [
                    azentspublicclient.models.managed_channel_default.ManagedChannelDefault(
                        id = '', 
                        provider_channel_id = '', 
                        route_id = '', 
                        agent_id = '', 
                        agent_name = '', 
                        status = 'active', 
                        configured_by_user_id = '', 
                        invalidated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invalidation_reason = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testManagedChannelDefaultListResponse(self):
        """Test ManagedChannelDefaultListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
