# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.runtime_desired_state import RuntimeDesiredState

class TestRuntimeDesiredState(unittest.TestCase):
    """RuntimeDesiredState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimeDesiredState(self):
        """Test RuntimeDesiredState"""
        # inst = RuntimeDesiredState()

if __name__ == '__main__':
    unittest.main()
