# coding: utf-8

"""
    Azents Public API

    Public read-only API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentspublicclient.models.kubernetes_pod_profile_spec_v2 import KubernetesPodProfileSpecV2

class TestKubernetesPodProfileSpecV2(unittest.TestCase):
    """KubernetesPodProfileSpecV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KubernetesPodProfileSpecV2:
        """Test KubernetesPodProfileSpecV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KubernetesPodProfileSpecV2`
        """
        model = KubernetesPodProfileSpecV2()
        if include_optional:
            return KubernetesPodProfileSpecV2(
                profile_kind = 'kubernetes_pod',
                contract_family = 'kubernetes.pod-profile',
                schema_version = 2,
                runner_resources = { },
                workspace_volume = { },
                network_policy = { },
                service_account_name = '',
                scheduling = { },
                dind = { },
                process_containment = { }
            )
        else:
            return KubernetesPodProfileSpecV2(
                profile_kind = 'kubernetes_pod',
                contract_family = 'kubernetes.pod-profile',
                schema_version = 2,
                runner_resources = { },
                workspace_volume = { },
                network_policy = { },
                service_account_name = '',
                scheduling = { },
                dind = { },
                process_containment = { },
        )
        """

    def testKubernetesPodProfileSpecV2(self):
        """Test KubernetesPodProfileSpecV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
