# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.docker_container_profile_spec_v1 import DockerContainerProfileSpecV1

class TestDockerContainerProfileSpecV1(unittest.TestCase):
    """DockerContainerProfileSpecV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DockerContainerProfileSpecV1:
        """Test DockerContainerProfileSpecV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DockerContainerProfileSpecV1`
        """
        model = DockerContainerProfileSpecV1()
        if include_optional:
            return DockerContainerProfileSpecV1(
                profile_kind = 'docker_container',
                contract_family = 'docker.container-profile',
                schema_version = 1,
                runner_resources = azentsadminclient.models.docker_container_resources.DockerContainerResources(
                    cpu_reservation_millicores = 1.0, 
                    cpu_limit_millicores = 1.0, 
                    memory_reservation_bytes = 1.0, 
                    memory_limit_bytes = 1.0, ),
                network_name = ''
            )
        else:
            return DockerContainerProfileSpecV1(
                profile_kind = 'docker_container',
                contract_family = 'docker.container-profile',
                schema_version = 1,
                runner_resources = azentsadminclient.models.docker_container_resources.DockerContainerResources(
                    cpu_reservation_millicores = 1.0, 
                    cpu_limit_millicores = 1.0, 
                    memory_reservation_bytes = 1.0, 
                    memory_limit_bytes = 1.0, ),
                network_name = '',
        )
        """

    def testDockerContainerProfileSpecV1(self):
        """Test DockerContainerProfileSpecV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
