# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.workspace_user_create_request import WorkspaceUserCreateRequest

class TestWorkspaceUserCreateRequest(unittest.TestCase):
    """WorkspaceUserCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceUserCreateRequest:
        """Test WorkspaceUserCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceUserCreateRequest`
        """
        model = WorkspaceUserCreateRequest()
        if include_optional:
            return WorkspaceUserCreateRequest(
                workspace_handle = '',
                user_id = '',
                name = '',
                role = 'owner'
            )
        else:
            return WorkspaceUserCreateRequest(
                workspace_handle = '',
                user_id = '',
                name = '',
                role = 'owner',
        )
        """

    def testWorkspaceUserCreateRequest(self):
        """Test WorkspaceUserCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
