# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.archive_retention_preview_request import ArchiveRetentionPreviewRequest

class TestArchiveRetentionPreviewRequest(unittest.TestCase):
    """ArchiveRetentionPreviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArchiveRetentionPreviewRequest:
        """Test ArchiveRetentionPreviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArchiveRetentionPreviewRequest`
        """
        model = ArchiveRetentionPreviewRequest()
        if include_optional:
            return ArchiveRetentionPreviewRequest(
                archived_session_retention_days = 0.0
            )
        else:
            return ArchiveRetentionPreviewRequest(
                archived_session_retention_days = 0.0,
        )
        """

    def testArchiveRetentionPreviewRequest(self):
        """Test ArchiveRetentionPreviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
