# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.api.runtime_provider_enrollment_v1_api import RuntimeProviderEnrollmentV1Api


class TestRuntimeProviderEnrollmentV1Api(unittest.TestCase):
    """RuntimeProviderEnrollmentV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = RuntimeProviderEnrollmentV1Api()

    def tearDown(self) -> None:
        pass

    def test_runtime_provider_enrollment_v1_issue_enrollment_grant(self) -> None:
        """Test case for runtime_provider_enrollment_v1_issue_enrollment_grant

        Issue Enrollment Grant
        """
        pass

    def test_runtime_provider_enrollment_v1_revoke_credential(self) -> None:
        """Test case for runtime_provider_enrollment_v1_revoke_credential

        Revoke Credential
        """
        pass


if __name__ == '__main__':
    unittest.main()
