# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.platform_git_hub_app_patch_request import PlatformGitHubAppPatchRequest

class TestPlatformGitHubAppPatchRequest(unittest.TestCase):
    """PlatformGitHubAppPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlatformGitHubAppPatchRequest:
        """Test PlatformGitHubAppPatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlatformGitHubAppPatchRequest`
        """
        model = PlatformGitHubAppPatchRequest()
        if include_optional:
            return PlatformGitHubAppPatchRequest(
                expected_version = 0.0,
                app_id = '',
                client_id = '',
                private_key = azentsadminclient.models.system_setting_secret_action_request.SystemSettingSecretActionRequest(
                    action = 'replace',
                    value = '', ),
                client_secret = azentsadminclient.models.system_setting_secret_action_request.SystemSettingSecretActionRequest(
                    action = 'replace',
                    value = '', )
            )
        else:
            return PlatformGitHubAppPatchRequest(
                expected_version = 0.0,
        )
        """

    def testPlatformGitHubAppPatchRequest(self):
        """Test PlatformGitHubAppPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
