# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.file_lifecycle_settings_response import FileLifecycleSettingsResponse

class TestFileLifecycleSettingsResponse(unittest.TestCase):
    """FileLifecycleSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileLifecycleSettingsResponse:
        """Test FileLifecycleSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileLifecycleSettingsResponse`
        """
        model = FileLifecycleSettingsResponse()
        if include_optional:
            return FileLifecycleSettingsResponse(
                archived_session_retention_days = 0.0,
                revision = 1.0,
                updated_by_user_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active_application = azentsadminclient.models.archive_retention_application_response.ArchiveRetentionApplicationResponse(
                    id = '', 
                    target_revision = 56, 
                    target_retention_days = 56, 
                    requested_by_user_id = '', 
                    status = 'pending', 
                    cursor_session_id = '', 
                    affected_count = 56, 
                    immediately_eligible_count = 56, 
                    cancelled_count = 56, 
                    scheduled_count = 56, 
                    skipped_count = 56, 
                    attempt_count = 56, 
                    lease_owner = '', 
                    lease_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    next_attempt_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_error_kind = '', 
                    last_error_summary = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return FileLifecycleSettingsResponse(
                archived_session_retention_days = 0.0,
                revision = 1.0,
                updated_by_user_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active_application = azentsadminclient.models.archive_retention_application_response.ArchiveRetentionApplicationResponse(
                    id = '', 
                    target_revision = 56, 
                    target_retention_days = 56, 
                    requested_by_user_id = '', 
                    status = 'pending', 
                    cursor_session_id = '', 
                    affected_count = 56, 
                    immediately_eligible_count = 56, 
                    cancelled_count = 56, 
                    scheduled_count = 56, 
                    skipped_count = 56, 
                    attempt_count = 56, 
                    lease_owner = '', 
                    lease_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    next_attempt_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_error_kind = '', 
                    last_error_summary = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testFileLifecycleSettingsResponse(self):
        """Test FileLifecycleSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
