# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.system_bootstrap_first_admin_request import SystemBootstrapFirstAdminRequest

class TestSystemBootstrapFirstAdminRequest(unittest.TestCase):
    """SystemBootstrapFirstAdminRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemBootstrapFirstAdminRequest:
        """Test SystemBootstrapFirstAdminRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemBootstrapFirstAdminRequest`
        """
        model = SystemBootstrapFirstAdminRequest()
        if include_optional:
            return SystemBootstrapFirstAdminRequest(
                email = '',
                password = ''
            )
        else:
            return SystemBootstrapFirstAdminRequest(
                email = '',
                password = '',
        )
        """

    def testSystemBootstrapFirstAdminRequest(self):
        """Test SystemBootstrapFirstAdminRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
