# coding: utf-8

"""
    Azents Admin API

    Admin CRUD API server for Azents

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from azentsadminclient.models.system_bootstrap_status_response import SystemBootstrapStatusResponse

class TestSystemBootstrapStatusResponse(unittest.TestCase):
    """SystemBootstrapStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemBootstrapStatusResponse:
        """Test SystemBootstrapStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemBootstrapStatusResponse`
        """
        model = SystemBootstrapStatusResponse()
        if include_optional:
            return SystemBootstrapStatusResponse(
                available = True
            )
        else:
            return SystemBootstrapStatusResponse(
                available = True,
        )
        """

    def testSystemBootstrapStatusResponse(self):
        """Test SystemBootstrapStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
